<?php
namespace App\Services\Finance;use App\Models\{User,WorkerPayoutReview};use Illuminate\Validation\ValidationException;
class WorkerPayoutReviewService{
 public function getOrCreateReview(User $w,string $type):WorkerPayoutReview{throw_unless(in_array($type,['identity','tax','payout_compliance'],true),ValidationException::withMessages(['type'=>'Valid payout review type is required.']));return WorkerPayoutReview::firstOrCreate(['worker_id'=>$w->id,'review_type'=>$type],['review_number'=>$this->number(),'worker_profile_id'=>$w->workerProfile?->id,'worker_payout_profile_id'=>$w->workerPayoutProfile?->id,'status'=>'draft','country'=>'NO','evidence_type'=>'text_attestation']);}
 public function submitReview(User $w,string $type,array $data):WorkerPayoutReview{$r=$this->getOrCreateReview($w,$type);throw_unless(in_array($r->status,['draft','changes_requested'],true),ValidationException::withMessages(['review'=>'Only draft or changes-requested reviews can be submitted.']));throw_if(blank($data['evidence_summary']??null),ValidationException::withMessages(['evidence_summary'=>'Evidence summary is required.']));$r->update(['status'=>'submitted','evidence_type'=>'text_attestation','evidence_summary'=>$data['evidence_summary'],'worker_note'=>$data['worker_note']??null,'submitted_at'=>now(),'requested_changes'=>null]);$this->event($r,$w,'submitted','Worker submitted text attestation. No external verification is implied.');$this->syncPayoutProfileReviewStatuses($w);return $r->refresh();}
 public function markInReview(WorkerPayoutReview $r,User $a):WorkerPayoutReview{return $this->transition($r,$a,'in_review','marked_in_review','Review started.');}
 public function requestChanges(WorkerPayoutReview $r,User $a,string $reason):WorkerPayoutReview{throw_unless($a->can('admin.worker_payout_reviews.request_changes'),ValidationException::withMessages(['actor'=>'Request-changes permission is required.']));$r->update(['status'=>'changes_requested','requested_changes'=>$reason,'reviewer_id'=>$a->id,'reviewed_at'=>now()]);$this->event($r,$a,'changes_requested',$reason);$this->syncPayoutProfileReviewStatuses($r->worker);return $r->refresh();}
 public function approve(WorkerPayoutReview $r,User $a,string $note,string $evidenceSummary):WorkerPayoutReview{$this->assertApprover($r,$a);throw_if(blank($note)||blank($evidenceSummary),ValidationException::withMessages(['approval'=>'Approval note and evidence summary are required.']));throw_if($r->worker_id===$a->id&&!$a->can('admin.worker_payout_reviews.override_separation'),ValidationException::withMessages(['separation'=>'Worker cannot self-approve payout review.']));$r->update(['status'=>'approved','reviewer_id'=>$a->id,'approved_by_id'=>$a->id,'reviewed_at'=>now(),'approved_at'=>now(),'reviewer_note'=>$note,'evidence_summary'=>$evidenceSummary]);$this->event($r,$a,'approved',$note);$this->syncPayoutProfileReviewStatuses($r->worker);return $r->refresh();}
 public function reject(WorkerPayoutReview $r,User $a,string $reason):WorkerPayoutReview{throw_unless($a->can('admin.worker_payout_reviews.reject'),ValidationException::withMessages(['actor'=>'Reject permission is required.']));$r->update(['status'=>'rejected','reviewer_id'=>$a->id,'rejected_by_id'=>$a->id,'reviewed_at'=>now(),'rejected_at'=>now(),'reviewer_note'=>$reason]);$this->event($r,$a,'rejected',$reason);$this->syncPayoutProfileReviewStatuses($r->worker);return $r->refresh();}
 public function getWorkerReviewReadiness(User $w):array{$reviews=WorkerPayoutReview::where('worker_id',$w->id)->get()->keyBy('review_type');$b=[];foreach(['identity','tax'] as $type)if($reviews->get($type)?->status!=='approved')$b[]=ucfirst($type).' payout review is not approved.';return ['reviews'=>$reviews,'ready'=>empty($b),'blockers'=>$b];}
 public function syncPayoutProfileReviewStatuses(User $w):void{$p=$w->workerPayoutProfile;if(!$p)return;$x=$this->getWorkerReviewReadiness($w)['reviews'];$p->update(['identity_profile_status'=>$x->get('identity')?->status==='approved'?'approved':($x->get('identity')?->status??'missing'),'tax_profile_status'=>$x->get('tax')?->status==='approved'?'approved':($x->get('tax')?->status??'missing')]);}
 private function transition($r,$a,$status,$event,$description){throw_unless($a->can('admin.worker_payout_reviews.manage'),ValidationException::withMessages(['actor'=>'Payout review management permission is required.']));$r->update(['status'=>$status,'reviewer_id'=>$a->id,'reviewed_at'=>now()]);$this->event($r,$a,$event,$description);return $r->refresh();}private function assertApprover($r,$a){$type=$r->review_type==='payout_compliance'?'compliance':$r->review_type;throw_unless($a->can('admin.worker_payout_reviews.'.$type.'.approve'),ValidationException::withMessages(['actor'=>ucfirst($type).' payout reviewer permission is required.']));}private function event($r,$a,$type,$d){$r->events()->create(['worker_id'=>$r->worker_id,'actor_id'=>$a->id,'event_type'=>$type,'description'=>$d,'created_at'=>now()]);}private function number(){do{$n='WPR-'.now()->format('Ymd').'-'.strtoupper(str()->random(6));}while(WorkerPayoutReview::where('review_number',$n)->exists());return $n;}
}
