<?php
namespace App\Services\Finance;
use App\Models\{User,WorkerPayoutProfile};
use Illuminate\Support\Facades\Crypt;
use Illuminate\Validation\ValidationException;
class WorkerPayoutProfileService {
 public function getOrCreateDraft(User $worker):WorkerPayoutProfile{return WorkerPayoutProfile::firstOrCreate(['worker_id'=>$worker->id],['worker_profile_id'=>$worker->workerProfile?->id,'status'=>'draft','country'=>'NO','currency'=>'NOK','payout_method'=>'manual_bank_review']);}
 public function updateDraft(User $worker,array $data):WorkerPayoutProfile{$p=$this->getOrCreateDraft($worker);throw_unless(in_array($p->status,['draft','changes_requested'],true),ValidationException::withMessages(['profile'=>'Only draft or changes-requested profiles can be updated.']));$safe=collect($data)->only(['payout_method','account_holder_name','country','currency'])->all();foreach(['bank_account','iban','swift_bic','vipps_phone'] as $key)if(filled($data[$key]??null)){$safe['encrypted_'.$key]=Crypt::encryptString((string)$data[$key]);$safe[$key.'_last_four']=substr((string)$data[$key],-4);}$p->update($safe+['status'=>'draft']);$this->event($p,$worker,'secret_updated','Worker updated encrypted payout profile fields.');return $p->refresh();}
 public function submit(User $worker):WorkerPayoutProfile{$p=$this->getOrCreateDraft($worker);throw_unless($this->hasMethodData($p),ValidationException::withMessages(['profile'=>'At least one payout method data field is required.']));$p->update(['status'=>'submitted','submitted_at'=>now(),'tax_profile_status'=>'pending_review','identity_profile_status'=>'pending_review']);$this->event($p,$worker,'submitted','Payout profile submitted for review. No payout was executed.');return $p->refresh();}
 public function requestChanges(WorkerPayoutProfile $p,User $a,string $reason):WorkerPayoutProfile{return $this->reviewTransition($p,$a,'changes_requested','changes_requested',$reason);}
 public function approve(WorkerPayoutProfile $p,User $a,string $note):WorkerPayoutProfile{throw_unless($a->can('admin.payouts.manage'),ValidationException::withMessages(['actor'=>'Payout management permission is required.']));throw_unless($p->tax_profile_status==='approved'&&$p->identity_profile_status==='approved',ValidationException::withMessages(['review'=>'Worker tax/identity payout review is not approved.']));throw_unless($this->hasMethodData($p),ValidationException::withMessages(['profile'=>'Payout method data is required.']));$p->update(['status'=>'approved','approved_at'=>now(),'approved_by_id'=>$a->id,'review_note'=>$note]);$this->event($p,$a,'approved',$note);return $p->refresh();}
 public function reject(WorkerPayoutProfile $p,User $a,string $reason):WorkerPayoutProfile{return $this->reviewTransition($p,$a,'rejected','rejected',$reason);}
 public function archive(WorkerPayoutProfile $p,User $a,string $reason):WorkerPayoutProfile{return $this->reviewTransition($p,$a,'archived','archived',$reason);}
 public function getReadiness(User $worker):array{$p=WorkerPayoutProfile::where('worker_id',$worker->id)->first();$b=[];if(!$p)$b[]='Worker payout profile is missing.';elseif($p->status!=='approved')$b[]='Worker payout profile is '.$p->status.'.';if($p&&($p->tax_profile_status!=='approved'||$p->identity_profile_status!=='approved'))$b[]='Worker tax/identity payout review is not approved.';return ['profile'=>$p,'ready'=>empty($b),'blockers'=>$b];}
 private function reviewTransition(WorkerPayoutProfile $p,User $a,string $status,string $event,string $reason):WorkerPayoutProfile{throw_unless($a->can('admin.payouts.manage'),ValidationException::withMessages(['actor'=>'Payout management permission is required.']));throw_if(blank($reason),ValidationException::withMessages(['reason'=>'Reason is required.']));$p->update(['status'=>$status,'rejected_at'=>$status==='rejected'?now():$p->rejected_at,'rejected_by_id'=>$status==='rejected'?$a->id:$p->rejected_by_id,'rejection_reason'=>$reason]);$this->event($p,$a,$event,$reason);return $p->refresh();}
 private function hasMethodData(WorkerPayoutProfile $p):bool{return filled($p->encrypted_bank_account)||filled($p->encrypted_iban)||filled($p->encrypted_vipps_phone);}
 private function event(WorkerPayoutProfile $p,User $a,string $type,string $description):void{$p->events()->create(['worker_id'=>$p->worker_id,'actor_id'=>$a->id,'event_type'=>$type,'description'=>$description,'created_at'=>now()]);}
}
