<?php
namespace App\Services\Finance;
use App\Models\{User,WorkerPayoutReview,WorkerPayoutReviewEvidence};
use App\Services\Security\FileScannerManager;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;
use Symfony\Component\HttpFoundation\StreamedResponse;
class WorkerPayoutEvidenceService{
 public function __construct(private FileScannerManager $scanners){}
 public function uploadEvidence(WorkerPayoutReview $r,User $a,UploadedFile $f,string $type):WorkerPayoutReviewEvidence{throw_unless($r->worker_id===$a->id||$a->can('admin.worker_payout_evidence.view'),ValidationException::withMessages(['actor'=>'Evidence upload is not authorized.']));throw_unless(in_array($type,['identity_document','tax_document','payout_document','other'],true),ValidationException::withMessages(['type'=>'Valid evidence type is required.']));throw_unless($f->isValid()&&$f->getSize()<=10485760&&$f->getMimeType()==='application/pdf',ValidationException::withMessages(['file'=>'Only private PDF evidence up to 10 MB is accepted. Images remain disabled because EXIF stripping is not configured.']));$path=$f->store('worker-payout-evidence/'.$r->worker_id.'/'.$r->id,'local');$e=WorkerPayoutReviewEvidence::create(['worker_payout_review_id'=>$r->id,'worker_id'=>$r->worker_id,'uploaded_by_id'=>$a->id,'status'=>'uploaded','evidence_type'=>$type,'original_filename'=>basename($f->getClientOriginalName()),'stored_disk'=>'local','stored_path'=>$path,'mime_type'=>$f->getMimeType(),'size_bytes'=>$f->getSize(),'sha256_hash'=>hash_file('sha256',Storage::disk('local')->path($path)),'visibility'=>'private','scan_status'=>'pending_scan']);$this->event($e,$a,'uploaded','Private PDF evidence uploaded. Upload does not approve review.');$this->event($e,$a,'scan_requested','Malware scan requested.');return $this->scan($e,$a);}
 public function canViewEvidence(WorkerPayoutReviewEvidence $e,User $a):array{$allowed=$e->worker_id===$a->id||$this->reviewerAllowed($e,$a,'view');return ['allowed'=>$allowed,'reason'=>$allowed?null:'Evidence access is not authorized.'];}
 public function canDownloadEvidence(WorkerPayoutReviewEvidence $e,User $a):array{if($e->worker_id===$a->id)return ['allowed'=>true,'reason'=>null];if(!$this->reviewerAllowed($e,$a,'download'))return ['allowed'=>false,'reason'=>'Evidence download is not authorized.'];return ['allowed'=>$e->scan_status==='clean','reason'=>$e->scan_status==='clean'?null:'Reviewer download is blocked until malware scan status is clean.'];}
 public function downloadEvidence(WorkerPayoutReviewEvidence $e,User $a):StreamedResponse{throw_unless($this->canDownloadEvidence($e,$a)['allowed'],ValidationException::withMessages(['actor'=>$this->canDownloadEvidence($e,$a)['reason']]));$this->event($e,$a,'downloaded','Private evidence downloaded.');return Storage::disk($e->stored_disk)->download($e->stored_path,$e->original_filename);}
 public function overrideDownload(WorkerPayoutReviewEvidence $e,User $a,string $reason):StreamedResponse{throw_unless($a->can('admin.worker_payout_evidence.download_override'),ValidationException::withMessages(['actor'=>'Download override permission is required.']));throw_if(blank($reason),ValidationException::withMessages(['reason'=>'Override reason is required.']));$e->update(['download_override_required'=>true,'download_override_reason'=>$reason,'download_override_by_id'=>$a->id,'download_override_at'=>now()]);$this->event($e,$a,'download_override_used',$reason);return Storage::disk($e->stored_disk)->download($e->stored_path,$e->original_filename);}
 public function rejectEvidence(WorkerPayoutReviewEvidence $e,User $a,string $reason):WorkerPayoutReviewEvidence{throw_unless($a->can('admin.worker_payout_evidence.reject'),ValidationException::withMessages(['actor'=>'Evidence rejection permission is required.']));$e->update(['status'=>'rejected','rejection_reason'=>$reason]);$this->event($e,$a,'rejected',$reason);return $e->refresh();}
 public function archiveEvidence(WorkerPayoutReviewEvidence $e,User $a,string $reason):WorkerPayoutReviewEvidence{throw_unless($a->can('admin.worker_payout_evidence.archive'),ValidationException::withMessages(['actor'=>'Evidence archive permission is required.']));$e->update(['status'=>'archived','reviewer_note'=>$reason]);$this->event($e,$a,'archived',$reason);return $e->refresh();}
 public function getEvidenceReadiness(WorkerPayoutReview $r):array{$x=WorkerPayoutReviewEvidence::where('worker_payout_review_id',$r->id)->get();$clean=$x->where('scan_status','clean')->count();return ['ready'=>$clean>0,'count'=>$x->count(),'clean'=>$clean,'blockers'=>$clean?[]:['Evidence malware scan is not clean.']];}
 private function scan(WorkerPayoutReviewEvidence $e,User $a):WorkerPayoutReviewEvidence{$result=$this->scanners->resolve()->scan(Storage::disk($e->stored_disk)->path($e->stored_path));$status=match($result->status){'clean'=>'clean','infected'=>'infected','failed'=>'scan_failed',default=>'scan_unavailable'};$update=['scan_status'=>$status,'scan_engine'=>$result->engine,'scan_signature'=>$result->signature,'scan_error'=>$result->message,'scanned_at'=>in_array($status,['clean','infected'],true)?now():null];if($status==='infected')$update+=['status'=>'quarantine','quarantined_at'=>now(),'quarantine_reason'=>'Malware scanner reported infected evidence.'];$e->update($update);$this->event($e,$a,'scan_'.$result->status,$result->message??'Scan completed.');if($status==='infected')$this->event($e,$a,'quarantined','Evidence quarantined after infected verdict.');return $e->refresh();}
 private function reviewerAllowed($e,$a,$action):bool{$type=$e->review->review_type==='payout_compliance'?'compliance':$e->review->review_type;return $a->can('admin.worker_payout_evidence.'.$action)&&$a->can('admin.worker_payout_reviews.'.$type.'.approve');}
 private function event($e,$a,$type,$d){$e->events()->create(['worker_payout_review_id'=>$e->worker_payout_review_id,'actor_id'=>$a->id,'event_type'=>$type,'description'=>$d,'created_at'=>now()]);}
}
