<?php
namespace App\Services\Finance;
use App\Models\{Order,User,WorkerSettlementEntry};
use Illuminate\Validation\ValidationException;
class WorkerSettlementService {
 public function __construct(private WorkerSettlementNumberGenerator $numbers){}
 public function calculateForOrder(Order $order,User $actor):WorkerSettlementEntry{return $this->persist($order,$actor,'created',null);}
 public function recalculateForOrder(Order $order,User $actor,string $reason):WorkerSettlementEntry{throw_if(blank($reason),ValidationException::withMessages(['reason'=>'Recalculation reason is required.']));return $this->persist($order,$actor,'recalculated',$reason);}
 public function getPayoutBlockers(Order $order):array{$b=[];$assignment=$order->activeDispatchAssignment();$invoice=$order->billingDocuments()->where('status','issued')->latest()->first();$proof=$order->completionProofs()->latest()->first();if(!$assignment)$b[]='Worker assignment is required.';if(!$invoice)$b[]='Issued invoice is required.';if(!$proof||$proof->status!=='accepted')$b[]=$proof?->status==='disputed'?'Customer disputed the completion proof.':'Customer completion confirmation is required.';if(!$order->paymentRecords()->where('status','captured')->exists())$b[]='Payment is not captured.';$b[]='Worker settlement rule is not configured.';return array_values(array_unique($b));}
 public function getSettlementReadiness(Order $order):array{$entry=$order->workerSettlementEntries()->latest()->first();$blockers=$this->getPayoutBlockers($order);return ['entry'=>$entry,'ready'=>empty($blockers),'blockers'=>$blockers,'reason'=>$blockers[0]??null];}
 public function getWorkerEarningsSummary(User $worker):array{$q=WorkerSettlementEntry::where('worker_id',$worker->id);return ['entries'=>$q->latest()->get(),'ready_amount'=>(float)(clone $q)->where('status','ready')->sum('worker_amount'),'paid_amount'=>(float)(clone $q)->where('status','paid')->sum('worker_amount'),'blocked_count'=>(clone $q)->whereIn('status',['blocked','pending_capture'])->count()];}
 public function canApproveSettlement(WorkerSettlementEntry $entry,User $actor):array{return ['allowed'=>$entry->status==='ready'&&$actor->can('admin.finance.manage'),'reason'=>$entry->status!=='ready'?'Settlement is not ready.':'Finance permission is required.'];}
 public function canMarkPaid(WorkerSettlementEntry $entry,User $actor):array{return ['allowed'=>false,'reason'=>'Payout provider/manual payout workflow is not configured.'];}
 private function persist(Order $order,User $actor,string $event,?string $reason):WorkerSettlementEntry{$assignment=$order->activeDispatchAssignment();$invoice=$order->billingDocuments()->where('status','issued')->latest()->first();$proof=$order->completionProofs()->latest()->first();$payment=$order->paymentRecords()->where('status','captured')->latest()->first();$blockers=$this->getPayoutBlockers($order);$status=$payment?'blocked':'pending_capture';$entry=WorkerSettlementEntry::updateOrCreate(['order_id'=>$order->id],['entry_number'=>WorkerSettlementEntry::where('order_id',$order->id)->value('entry_number')??$this->numbers->generate(),'worker_id'=>$assignment?->assigned_user_id,'worker_profile_id'=>$assignment?->assignedUser?->workerProfile?->id,'dispatch_assignment_id'=>$assignment?->id,'billing_document_id'=>$invoice?->id,'payment_record_id'=>$payment?->id,'completion_proof_id'=>$proof?->id,'status'=>$status,'currency'=>$invoice?->currency??$order->currency??'NOK','gross_amount'=>$invoice?->total_amount,'platform_fee_amount'=>null,'worker_amount'=>null,'calculation_basis'=>'Blocked until an explicit worker settlement rule is configured.','blocker_reason'=>implode(' ',$blockers),'created_by_id'=>$actor->id,'updated_by_id'=>$actor->id]);$entry->events()->create(['order_id'=>$order->id,'worker_id'=>$entry->worker_id,'actor_id'=>$actor->id,'event_type'=>$event,'to_value'=>$status,'description'=>$reason??'Settlement ledger calculated from persisted order evidence; payout remains blocked.','created_at'=>now()]);return $entry;}
}
