<?php
namespace App\Services\Finance;use App\Models\{User,WorkerPayoutReview,WorkerPayoutReviewEvidence};use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\ValidationException;use Symfony\Component\HttpFoundation\StreamedResponse;
class WorkerPayoutEvidenceService{
 public function uploadEvidence(WorkerPayoutReview $r,User $a,UploadedFile $f,string $type):WorkerPayoutReviewEvidence{throw_unless($r->worker_id===$a->id||$a->can('admin.worker_payout_evidence.view'),ValidationException::withMessages(['actor'=>'Evidence upload is not authorized.']));throw_unless(in_array($type,['identity_document','tax_document','payout_document','other'],true),ValidationException::withMessages(['type'=>'Valid evidence type is required.']));throw_unless($f->isValid()&&$f->getSize()<=10485760&&$f->getMimeType()==='application/pdf',ValidationException::withMessages(['file'=>'Only private PDF evidence up to 10 MB is accepted. Images remain disabled because EXIF stripping is not configured.']));$path=$f->store('worker-payout-evidence/'.$r->worker_id.'/'.$r->id,'local');$e=WorkerPayoutReviewEvidence::create(['worker_payout_review_id'=>$r->id,'worker_id'=>$r->worker_id,'uploaded_by_id'=>$a->id,'status'=>'uploaded','evidence_type'=>$type,'original_filename'=>basename($f->getClientOriginalName()),'stored_disk'=>'local','stored_path'=>$path,'mime_type'=>$f->getMimeType(),'size_bytes'=>$f->getSize(),'sha256_hash'=>hash_file('sha256',Storage::disk('local')->path($path)),'visibility'=>'private']);$this->event($e,$a,'uploaded','Private PDF evidence uploaded. Upload does not approve review.');return $e;}
 public function canViewEvidence(WorkerPayoutReviewEvidence $e,User $a):array{$allowed=$e->worker_id===$a->id||$this->reviewerAllowed($e,$a,'view');return ['allowed'=>$allowed,'reason'=>$allowed?null:'Evidence access is not authorized.'];}
 public function canDownloadEvidence(WorkerPayoutReviewEvidence $e,User $a):array{return $this->canViewEvidence($e,$a);}
 public function downloadEvidence(WorkerPayoutReviewEvidence $e,User $a):StreamedResponse{throw_unless($this->canDownloadEvidence($e,$a)['allowed'],ValidationException::withMessages(['actor'=>'Evidence download is not authorized.']));$this->event($e,$a,'downloaded','Private evidence downloaded.');return Storage::disk($e->stored_disk)->download($e->stored_path,$e->original_filename);}
 public function rejectEvidence(WorkerPayoutReviewEvidence $e,User $a,string $reason):WorkerPayoutReviewEvidence{throw_unless($a->can('admin.worker_payout_evidence.reject'),ValidationException::withMessages(['actor'=>'Evidence rejection permission is required.']));$e->update(['status'=>'rejected','rejection_reason'=>$reason]);$this->event($e,$a,'rejected',$reason);return $e->refresh();}
 public function archiveEvidence(WorkerPayoutReviewEvidence $e,User $a,string $reason):WorkerPayoutReviewEvidence{throw_unless($a->can('admin.worker_payout_evidence.archive'),ValidationException::withMessages(['actor'=>'Evidence archive permission is required.']));$e->update(['status'=>'archived','reviewer_note'=>$reason]);$this->event($e,$a,'archived',$reason);return $e->refresh();}
 public function getEvidenceReadiness(WorkerPayoutReview $r):array{$count=WorkerPayoutReviewEvidence::where('worker_payout_review_id',$r->id)->whereIn('status',['uploaded','accepted_for_review'])->count();return ['ready'=>$count>0,'count'=>$count,'blockers'=>$count?['Virus scanning is not configured; evidence is private-review only.']:['Private review evidence is required.','Virus scanning is not configured; evidence is private-review only.']];}
 private function reviewerAllowed($e,$a,$action):bool{$type=$e->review->review_type==='payout_compliance'?'compliance':$e->review->review_type;return $a->can('admin.worker_payout_evidence.'.$action)&&$a->can('admin.worker_payout_reviews.'.$type.'.approve');}private function event($e,$a,$type,$d){$e->events()->create(['worker_payout_review_id'=>$e->worker_payout_review_id,'actor_id'=>$a->id,'event_type'=>$type,'description'=>$d,'created_at'=>now()]);}
}
