<?php
return [
'admin'=>['dashboard'=>'Панель','operations'=>'Операции','dispatch'=>'Диспетчерская','orders'=>'Заказы','people'=>'Персонал','services'=>'Услуги','finance'=>'Финансы','support'=>'Поддержка','content'=>'Контент','system'=>'Система'],
'modules'=>['operations'=>'Операционный центр','dispatch'=>'Диспетчерский центр','live_map'=>'Карта операций','orders'=>'Центр заказов','people'=>'Персонал и исполнители','services'=>'Каталог услуг','finance'=>'Финансовый контроль','support'=>'Центр поддержки','content'=>'CMS и SEO','system'=>'Система и безопасность','translations'=>'Менеджер переводов'],
'descriptions'=>['operations'=>'Контроль операционной готовности','dispatch'=>'Назначения и диспетчерские операции','live_map'=>'Только реальные GPS-сигналы исполнителей','orders'=>'Жизненный цикл и очередь действий по заказам','people'=>'Исполнители, заявки и комплаенс','services'=>'Сценарии услуг и поля заявки','finance'=>'Ценообразование и готовность платежей','support'=>'Тикеты и операционные инциденты','content'=>'Публичный контент и SEO','system'=>'Безопасность, настройки и аудит','translations'=>'Управление переводами админки и продукта'],
'common'=>['module_switcher'=>'Переключатель модулей BiKuBe Admin OS','status'=>'Статус','action'=>'Действие','actions'=>'Действия','save'=>'Сохранить','edit'=>'Изменить','open'=>'Открыть','download'=>'Скачать','approve'=>'Одобрить','reject'=>'Отклонить','pending'=>'Ожидает','approved'=>'Одобрено','rejected'=>'Отклонено','expired'=>'Истёк','not_connected'=>'Не подключено','not_exposed'=>'Не опубликовано','no_data'=>'Нет данных','back_to_admin'=>'Назад в Admin OS','open_real_route'=>'Открыть рабочий маршрут'],
'documents'=>['title'=>'Документы исполнителей','document_type'=>'Тип документа','required'=>'Обязательный','compliance_status'=>'Статус комплаенса','risk_level'=>'Уровень риска','evidence'=>'Подтверждение','manually_verified'=>'Проверено вручную','expires_at'=>'Срок действия','missing_evidence'=>'Нет подтверждения','ready_for_review'=>'Готово к проверке','private_download'=>'Приватное скачивание с аудитом','verification_note'=>'Примечание проверки','rejection_reason'=>'Причина отклонения'],
'settings'=>['platform'=>'Настройки платформы','operations'=>'Настройки операций','map'=>'Настройки карты','payment_disabled'=>'Платёжный провайдер ещё не подключён.','tracking_disabled'=>'Отслеживание для клиента ещё не опубликовано.'],
'system_security'=>['title'=>'Система и безопасность','back_to_admin'=>'Назад в Admin OS','kicker'=>'BiKuBe Next / Система','description'=>'Реальный статус среды, безопасности и пакетов.','operational_modules'=>'Операционные модули','installed_foundation_status'=>'Статус установленной основы','security_foundation'=>'Основа безопасности','auth_rbac_audit'=>'Авторизация, RBAC и аудит','security_checklist'=>'Чеклист безопасности'],
'localization'=>['choose_language'=>'Выберите язык','title'=>'Менеджер переводов','coverage'=>'Покрытие перевода','missing'=>'Отсутствующие переводы','fallback'=>'Резервный язык'],
'status'=>['blocked'=>'Заблокировано','ready'=>'Готово','pending'=>'Ожидает','completed'=>'Завершено','verified'=>'Проверено','recurring'=>'Повторяется'],
'blockers'=>['payment_not_captured'=>'Платёж не получен.','payout_provider_not_configured'=>'Провайдер выплат не настроен.','settlement_rule_not_active'=>'Правило расчёта не активно.','worker_payout_profile_not_approved'=>'Профиль выплат исполнителя не одобрен.','scanner_disabled'=>'Сканер отключён.','malware_scanning_not_configured'=>'Сканирование на вредоносное ПО не настроено.','reviewer_access_not_active'=>'Доступ проверяющего не активен.','audit_export_download_permission_required'=>'Требуется разрешение на скачивание аудиторского экспорта.','customer_completion_required'=>'Требуется подтверждение выполнения от клиента.','private_document_policy_required'=>'Приватная загрузка документов требует утверждённой политики безопасности медиафайлов.'],
'dashboard'=>['kicker'=>'Операции в Нарвике','title'=>'Обзор оператора','description'=>'Реальные очереди и текущие блокировки.','payment_provider_not_connected'=>'Платёжный провайдер: не подключён','orders_needing_action'=>'Заказы, требующие действий','unassigned'=>'Не назначено','dispatch_ready'=>'Готово к диспетчеризации','applications'=>'Заявки','documents_pending'=>'Документы на рассмотрении','eligible_workers'=>'Подходящие исполнители','next_operational_action'=>'Следующее операционное действие','latest_order'=>'Последний заказ','latest_application'=>'Последняя заявка','assignment_blocker'=>'Причина блокировки назначения','eligible_worker_available'=>'Доступен подходящий исполнитель','no_eligible_worker'=>'Нет одобренного онлайн-исполнителя с нужными возможностями','open_dispatch_queue'=>'Открыть очередь диспетчеризации','review_worker_applications'=>'Проверить заявки исполнителей','review_worker_documents'=>'Проверить документы исполнителей','open_orders'=>'Открыть заказы','open_pricing_rules'=>'Открыть правила ценообразования','action_required_now'=>'Требуется действие сейчас','open_queue'=>'Открыть очередь','no_submitted_applications'=>'Нет поданных заявок','review_documents'=>'Проверить документы','no_pending_documents'=>'Нет документов на рассмотрении','mark_dispatch_ready'=>'Отметить готовым к диспетчеризации','assign_eligible_worker'=>'Назначить подходящего исполнителя','worker_available'=>'Исполнитель доступен','blocked_no_eligible_worker'=>'Заблокировано: нет подходящего исполнителя','review_manual_quote'=>'Проверить ручное предложение','open_finance_control'=>'Открыть финансовый контроль','unavailable_modules'=>'Недоступные модули','unavailable_modules_list'=>'Платёжный провайдер · GPS · живая карта','unavailable_modules_detail'=>'Эти возможности не отображаются как рабочие действия.'],
'operations'=>['kicker'=>'BiKuBe Next / Операции','title'=>'Операционный центр','description'=>'Реальная панель готовности к запуску платформы в Нарвике. Страница показывает фактическое состояние системы и не использует выдуманные операционные данные.','status_label'=>'Состояние операций','skeleton_foundation'=>'Базовая структура','no_legacy_data'=>'Устаревшие данные не подключены','no_fake_data'=>'Без фальшивых GPS, заказов и платежей','foundation_summary'=>'Обзор базовой готовности','operational_posture'=>'Операционная готовность','foundation_only'=>'Только базовая основа','foundation_only_detail'=>'Готово для реальных доменных модулей, но не для производственной диспетчеризации.','launch_city'=>'Город запуска','narvik_first'=>'Сначала Нарвик','narvik_detail'=>'Норвежские ожидания и границы соответствия остаются видимыми.','data_policy'=>'Политика данных','honest_state'=>'Честное состояние','honest_state_detail'=>'Без условных чисел, фальшивых очередей и фальшивых карт.','runtime_evidence'=>'Данные среды выполнения','current_foundation_checks'=>'Текущие проверки основы','installed_modules'=>'Установленные операционные модули','module_foundation_wiring'=>'Подключение базовых модулей','readiness_gates'=>'Условия готовности','real_operations_blockers'=>'Что блокирует реальные операции','operations_rail'=>'Операционная панель','admin_routes'=>'Страницы Admin OS','route_map'=>'Карта базовых маршрутов','action_honesty'=>'Прозрачность действий','action_classification'=>'Видимая классификация действий'],
'operational_states'=>['safe'=>'Безопасно','review'=>'Требует проверки'],
'admin_ui'=>[
'Dispatch Center'=>'Диспетчерский центр','Live Operations Map'=>'Карта активных операций',
'Actions'=>'Действия','Active'=>'Активно','Add'=>'Добавить','Admin OS routes'=>'Страницы Admin OS','All'=>'Все','Amount'=>'Сумма','Approved'=>'Одобрено','Archive'=>'Архивировать','Assigned'=>'Назначено','Blocked'=>'Заблокировано','Cancel'=>'Отмена','Completed'=>'Завершено','Configuration'=>'Настройки','Create'=>'Создать','Current status'=>'Текущее состояние','Customer'=>'Клиент','Dashboard'=>'Обзор','Date'=>'Дата','Delete'=>'Удалить','Description'=>'Описание','Disabled'=>'Отключено','Download'=>'Скачать','Edit'=>'Изменить','Email'=>'Электронная почта','Enabled'=>'Включено','Evidence'=>'Подтверждение','Export'=>'Экспортировать','Finance'=>'Финансы','Finance Control'=>'Финансовый контроль','Name'=>'Название','Next action'=>'Следующее действие','No data'=>'Нет данных','Open'=>'Открыть','Operations'=>'Операции','Orders'=>'Заказы','Orders Hub'=>'Центр заказов','Owner'=>'Владелец','Payment provider is not configured.'=>'Платёжный провайдер не настроен.','Payment is not captured.'=>'Платёж не получен.','Pending'=>'Ожидает','People'=>'Люди','Priority'=>'Приоритет','Provider'=>'Провайдер','Ready'=>'Готово','Reason'=>'Причина','Reject'=>'Отклонить','Rejected'=>'Отклонено','Review'=>'Проверка','Reviewer'=>'Проверяющий','Save'=>'Сохранить','Security'=>'Безопасность','Security Governance'=>'Управление безопасностью','Service Catalog'=>'Каталог услуг','Services'=>'Услуги','Settings'=>'Настройки','Status'=>'Статус','Submit'=>'Отправить','Support'=>'Поддержка','Support Center'=>'Центр поддержки','System'=>'Система','System & Security'=>'Система и безопасность','Tax review is not approved.'=>'Налоговая проверка не одобрена.','Translation Manager'=>'Менеджер переводов','Unassigned'=>'Не назначено','Updated at'=>'Обновлено','User'=>'Пользователь','View'=>'Просмотреть','Worker'=>'Исполнитель','Worker payout profile is not approved.'=>'Профиль выплат исполнителя не одобрен.','Worker settlement rule is not configured.'=>'Правило расчёта исполнителя не настроено.',
],
];
