<?php
return [
'admin'=>['dashboard'=>'Панель','operations'=>'Операции','dispatch'=>'Диспетчерская','orders'=>'Заказы','people'=>'Персонал','services'=>'Услуги','finance'=>'Финансы','support'=>'Поддержка','content'=>'Контент','system'=>'Система'],
'modules'=>['operations'=>'Операционный центр','dispatch'=>'Диспетчерский центр','live_map'=>'Карта операций','orders'=>'Центр заказов','people'=>'Персонал и исполнители','services'=>'Каталог услуг','finance'=>'Финансовый контроль','support'=>'Центр поддержки','content'=>'CMS и SEO','system'=>'Система и безопасность','translations'=>'Менеджер переводов'],
'descriptions'=>['operations'=>'Контроль операционной готовности','dispatch'=>'Назначения и диспетчерские операции','live_map'=>'Только реальные GPS-сигналы исполнителей','orders'=>'Жизненный цикл и очередь действий по заказам','people'=>'Исполнители, заявки и комплаенс','services'=>'Сценарии услуг и поля заявки','finance'=>'Ценообразование и готовность платежей','support'=>'Тикеты и операционные инциденты','content'=>'Публичный контент и SEO','system'=>'Безопасность, настройки и аудит','translations'=>'Управление переводами админки и продукта'],
'common'=>['module_switcher'=>'Переключатель модулей BiKuBe Admin OS','status'=>'Статус','action'=>'Действие','actions'=>'Действия','save'=>'Сохранить','edit'=>'Изменить','open'=>'Открыть','download'=>'Скачать','approve'=>'Одобрить','reject'=>'Отклонить','pending'=>'Ожидает','approved'=>'Одобрено','rejected'=>'Отклонено','expired'=>'Истёк','not_connected'=>'Не подключено','not_exposed'=>'Не опубликовано','no_data'=>'Нет данных','back_to_admin'=>'Назад в Admin OS','open_real_route'=>'Открыть рабочий маршрут'],
'documents'=>['title'=>'Документы исполнителей','document_type'=>'Тип документа','required'=>'Обязательный','compliance_status'=>'Статус комплаенса','risk_level'=>'Уровень риска','evidence'=>'Подтверждение','manually_verified'=>'Проверено вручную','expires_at'=>'Срок действия','missing_evidence'=>'Нет подтверждения','ready_for_review'=>'Готово к проверке','private_download'=>'Приватное скачивание с аудитом','verification_note'=>'Примечание проверки','rejection_reason'=>'Причина отклонения'],
'settings'=>['platform'=>'Настройки платформы','operations'=>'Настройки операций','map'=>'Настройки карты','payment_disabled'=>'Платёжный провайдер ещё не подключён.','tracking_disabled'=>'Отслеживание для клиента ещё не опубликовано.'],
'system_security'=>['title'=>'Система и безопасность','back_to_admin'=>'Назад в Admin OS','kicker'=>'BiKuBe Next / Система','description'=>'Реальный статус среды, безопасности и пакетов.','operational_modules'=>'Операционные модули','installed_foundation_status'=>'Статус установленной основы','security_foundation'=>'Основа безопасности','auth_rbac_audit'=>'Авторизация, RBAC и аудит','security_checklist'=>'Чеклист безопасности'],
];
