<?php
return [
'admin'=>['dashboard'=>'Dashboard','operations'=>'Operations','dispatch'=>'Dispatch','orders'=>'Orders','people'=>'People','services'=>'Services','finance'=>'Finance','support'=>'Support','content'=>'Content','system'=>'System'],
'modules'=>['operations'=>'Operations Command Center','dispatch'=>'Dispatch Center','live_map'=>'Live Operations Map','orders'=>'Orders Hub','people'=>'People & Workforce','services'=>'Service Catalog','finance'=>'Finance Control','support'=>'Support Center','content'=>'CMS & SEO','system'=>'System & Security','translations'=>'Translation Manager'],
'descriptions'=>['operations'=>'Operational readiness cockpit','dispatch'=>'Assignment and dispatch operations','live_map'=>'Real worker GPS pings only','orders'=>'Order lifecycle and action queue','people'=>'Workers, applications and compliance','services'=>'Service scenarios and intake fields','finance'=>'Pricing and payment readiness','support'=>'Tickets and operational incidents','content'=>'Public content and SEO','system'=>'Security, settings and audit','translations'=>'Manage admin and product translations'],
'common'=>['module_switcher'=>'BiKuBe Admin OS module switcher','status'=>'Status','action'=>'Action','actions'=>'Actions','save'=>'Save','edit'=>'Edit','open'=>'Open','download'=>'Download','approve'=>'Approve','reject'=>'Reject','pending'=>'Pending','approved'=>'Approved','rejected'=>'Rejected','expired'=>'Expired','not_connected'=>'Not connected','not_exposed'=>'Not exposed','no_data'=>'No data','back_to_admin'=>'Back to Admin OS','open_real_route'=>'Open real route'],
'documents'=>['title'=>'Worker Documents','document_type'=>'Document type','required'=>'Required','compliance_status'=>'Compliance status','risk_level'=>'Risk level','evidence'=>'Evidence','manually_verified'=>'Manually verified','expires_at'=>'Expires at','missing_evidence'=>'Missing evidence','ready_for_review'=>'Ready for review','private_download'=>'Private audited download','verification_note'=>'Verification note','rejection_reason'=>'Rejection reason'],
'settings'=>['platform'=>'Platform Settings','operations'=>'Operations Settings','map'=>'Map Settings','payment_disabled'=>'Payment provider adapter is not connected yet.','tracking_disabled'=>'Customer tracking is not exposed yet.'],
'system_security'=>['title'=>'System & Security','back_to_admin'=>'Back to Admin OS','kicker'=>'BiKuBe Next / System','description'=>'Real runtime, security and package readiness.','operational_modules'=>'Operational modules','installed_foundation_status'=>'Installed foundation status','security_foundation'=>'Security foundation','auth_rbac_audit'=>'Auth, RBAC and audit packages','security_checklist'=>'Security checklist'],
'localization'=>['choose_language'=>'Choose language','title'=>'Translation Manager','coverage'=>'Translation coverage','missing'=>'Missing translations','fallback'=>'Fallback language'],
'status'=>['blocked'=>'Blocked','ready'=>'Ready','pending'=>'Pending','completed'=>'Completed','verified'=>'Verified','recurring'=>'Recurring'],
'blockers'=>['payment_not_captured'=>'Payment is not captured.','payout_provider_not_configured'=>'Payout provider is not configured.','settlement_rule_not_active'=>'Settlement rule is not active.','worker_payout_profile_not_approved'=>'Worker payout profile is not approved.','scanner_disabled'=>'Scanner is disabled.','malware_scanning_not_configured'=>'Malware scanning is not configured.','reviewer_access_not_active'=>'Reviewer access is not active.','audit_export_download_permission_required'=>'Audit export download permission is required.','customer_completion_required'=>'Customer completion confirmation is required.','private_document_policy_required'=>'Private document upload requires an approved media security policy.'],
];
