<?php
namespace App\Services\Security;
use App\Models\{EvidenceRetentionJob,User,WorkerPayoutReviewEvidence};use App\Settings\SecurityFileSettings;use Carbon\Carbon;use Illuminate\Support\Collection;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
class EvidenceRetentionJobService {
 public function getCandidates(?Carbon $cutoff=null):Collection{$cutoff??=now();return WorkerPayoutReviewEvidence::with('review')->where(function($q)use($cutoff){$q->whereDate('retention_until','<=',$cutoff)->orWhere('scheduled_deletion_at','<=',$cutoff);})->get()->filter(fn($e)=>$this->canDeleteEvidence($e)['allowed'])->values();}
 public function createDryRun(User $actor,?Carbon $cutoff=null):EvidenceRetentionJob{$c=$this->getCandidates($cutoff);$job=EvidenceRetentionJob::create(['job_number'=>$this->number(),'status'=>'dry_run_completed','mode'=>'dry_run','candidate_count'=>$c->count(),'cutoff_date'=>($cutoff??now())->toDateString(),'requested_by_id'=>$actor->id,'requested_at'=>now(),'notes'=>'Dry run only; no evidence deleted.']);foreach($c as $e)$job->items()->create(['evidence_id'=>$e->id,'status'=>'candidate','reason'=>'Retention conditions passed in dry run.']);return $job->refresh();}
 public function approveJob(EvidenceRetentionJob $job,User $actor,string $reason):EvidenceRetentionJob{if(!$actor->can('admin.security.retention.manage'))throw ValidationException::withMessages(['permission'=>'Retention management permission is required.']);if(blank($reason))throw ValidationException::withMessages(['reason'=>'Approval reason is required.']);$job->update(['status'=>'approved','mode'=>'approved_delete','approved_by_id'=>$actor->id,'approved_at'=>now(),'notes'=>$reason]);return $job->refresh();}
 public function executeApprovedJob(EvidenceRetentionJob $job,User $actor):EvidenceRetentionJob{$s=app(SecurityFileSettings::class);$blockers=[];if(!$actor->can('admin.security.retention.manage'))$blockers[]='Retention management permission is required.';if(!$s->evidence_retention_enabled)$blockers[]='Evidence retention deletion is disabled.';if($s->evidence_retention_dry_run_only)$blockers[]='Evidence retention is configured for dry-run only.';if($job->status!=='approved')$blockers[]='Retention job is not approved.';if($blockers)throw ValidationException::withMessages(['retention'=>implode(' ',$blockers)]);throw ValidationException::withMessages(['retention'=>'Physical deletion requires a separately approved controlled execution task.']);}
 public function canDeleteEvidence(WorkerPayoutReviewEvidence $e):array{$active=in_array($e->review?->status,['draft','submitted','in_review','changes_requested'],true);$passed=($e->scheduled_deletion_at?->isPast()??false)||($e->retention_until?->isPast()??false);return ['allowed'=>$passed&&!$active,'reason'=>$active?'Evidence is linked to an active or pending review.':($passed?'Retention date has passed.':'Retention date has not passed.')];}
 private function number():string{do{$n='ERJ-'.now()->format('Ymd').'-'.Str::upper(Str::random(6));}while(EvidenceRetentionJob::where('job_number',$n)->exists());return $n;}
}
