<?php
namespace App\Services\Security;
use App\Models\{SecurityAccessReviewCycle,SecurityAccessReviewEvent,SecurityGovernanceNotification,User};use Illuminate\Support\Str;
class SecurityGovernanceNotificationService {
 public function createOrUpdateNotification(string $type,string $severity,string $subject,array $data):SecurityGovernanceNotification{$n=SecurityGovernanceNotification::firstOrNew(['type'=>$type,'related_type'=>$data['related_type']??null,'related_id'=>(string)($data['related_id']??'') ,'status'=>'open']);if(!$n->exists)$n->notification_number='SGN-'.now()->format('Ymd').'-'.Str::upper(Str::random(6));$n->fill(['severity'=>$severity,'subject'=>$subject,'message'=>$data['message']??null,'assigned_to_id'=>$data['assigned_to_id']??null,'created_by_id'=>$data['created_by_id']??null,'metadata'=>$data['metadata']??null])->save();$this->event($n,null,'created',$subject);return $n;}
 public function acknowledge(SecurityGovernanceNotification $n,User $a,string $note):SecurityGovernanceNotification{$n->update(['status'=>'acknowledged','acknowledged_by_id'=>$a->id,'acknowledged_at'=>now()]);$this->event($n,$a,'acknowledged',$note);return $n->refresh();}
 public function resolve(SecurityGovernanceNotification $n,User $a,string $note):SecurityGovernanceNotification{$n->update(['status'=>'resolved','resolved_by_id'=>$a->id,'resolved_at'=>now()]);$this->event($n,$a,'resolved',$note);return $n->refresh();}
 public function dismiss(SecurityGovernanceNotification $n,User $a,string $reason):SecurityGovernanceNotification{$n->update(['status'=>'dismissed']);$this->event($n,$a,'dismissed',$reason);return $n->refresh();}
 public function escalateOverdue(?User $actor=null):int{$count=0;SecurityAccessReviewCycle::where('status','open')->where('due_at','<',now())->each(function($c)use($actor,&$count){$this->createOrUpdateNotification('access_review_overdue','critical',"Access review {$c->cycle_number} is overdue",['related_type'=>SecurityAccessReviewCycle::class,'related_id'=>$c->id,'created_by_id'=>$actor?->id,'message'=>'Database/in-app escalation only. No external email or SMS was sent.']);SecurityAccessReviewEvent::create(['security_access_review_cycle_id'=>$c->id,'actor_id'=>$actor?->id,'event_type'=>'overdue_escalated','description'=>'Overdue access review escalated in database governance notifications.','created_at'=>now()]);$count++;});return $count;}
 public function getNotificationReadiness():array{return ['open'=>SecurityGovernanceNotification::where('status','open')->count(),'critical'=>SecurityGovernanceNotification::where('status','open')->where('severity','critical')->count(),'resolved'=>SecurityGovernanceNotification::where('status','resolved')->count(),'external_delivery'=>false];}
 private function event($n,?User $a,$t,$d):void{$n->events()->create(['actor_id'=>$a?->id,'event_type'=>$t,'description'=>$d,'created_at'=>now()]);}
}
