<?php
namespace App\Services\Security;
use App\Models\{SecurityAccessReviewCycle,SecurityAccessReviewEvent,SecurityAccessReviewItem,SecurityReviewerAccess,User};use Carbon\Carbon;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
class SecurityAccessReviewService {
 public function createCycle(User $actor,array $data=[]):SecurityAccessReviewCycle{$this->permit($actor,'admin.security.access_review.manage');$c=SecurityAccessReviewCycle::create(['cycle_number'=>'SAR-'.now()->format('Ymd').'-'.Str::upper(Str::random(6)),'status'=>'draft','review_type'=>$data['review_type']??'reviewer_access','scope'=>$data['scope']??null,'opened_by_id'=>$actor->id,'due_at'=>$data['due_at']??now()->addDays(14),'notes'=>$data['notes']??null]);$this->event($c,null,$actor,'cycle_created','Access review cycle created.');return $c;}
 public function openCycle(SecurityAccessReviewCycle $c,User $a):SecurityAccessReviewCycle{$this->permit($a,'admin.security.access_review.manage');$c->update(['status'=>'open','opened_by_id'=>$a->id,'opened_at'=>now()]);$this->event($c,null,$a,'opened','Access review opened.');return $c->refresh();}
 public function populateReviewerAccessItems(SecurityAccessReviewCycle $c,User $a):int{$this->permit($a,'admin.security.access_review.manage');$n=0;SecurityReviewerAccess::each(function($x)use($c,$a,&$n){$item=$c->items()->firstOrCreate(['security_reviewer_access_id'=>$x->id],['user_id'=>$x->user_id,'status'=>'pending']);$this->event($c,$item,$a,'item_added','Reviewer access added to cycle.');$n++;});return $n;}
 public function decideItem(SecurityAccessReviewItem $i,User $a,string $decision,?string $note=null,?Carbon $extendTo=null):SecurityAccessReviewItem{$this->permit($a,'admin.security.access_review.decide');if($i->user_id===$a->id&&!$a->hasAnyRole(['owner','admin']))throw ValidationException::withMessages(['separation'=>'Reviewer cannot decide their own access review.']);if(blank($note)||!in_array($decision,['keep','revoke','extend','skipped'],true))throw ValidationException::withMessages(['decision'=>'Valid decision and note are required.']);if($decision==='revoke')app(SecurityReviewerAccessService::class)->revokeAccess($i->access,$a,$note);if($decision==='extend'){if(!$extendTo)throw ValidationException::withMessages(['extend'=>'Extension date is required.']);app(SecurityReviewerAccessService::class)->extendAccess($i->access,$a,$extendTo,$note);}$i->update(['status'=>$decision,'recommendation'=>$decision,'reviewer_note'=>$note,'decided_by_id'=>$a->id,'decided_at'=>now()]);$this->event($i->cycle,$i,$a,'decision_'.$decision,$note);return $i->refresh();}
 public function completeCycle(SecurityAccessReviewCycle $c,User $a,string $note):SecurityAccessReviewCycle{$this->permit($a,'admin.security.access_review.manage');if($c->items()->where('status','pending')->exists())throw ValidationException::withMessages(['cycle'=>'All access review items must be decided before completion.']);$c->update(['status'=>'completed','completed_by_id'=>$a->id,'completed_at'=>now(),'notes'=>$note]);$this->event($c,null,$a,'completed',$note);return $c->refresh();}
 public function cancelCycle(SecurityAccessReviewCycle $c,User $a,string $reason):SecurityAccessReviewCycle{$this->permit($a,'admin.security.access_review.manage');$c->update(['status'=>'cancelled','notes'=>$reason]);$this->event($c,null,$a,'cancelled',$reason);return $c->refresh();}
 public function getAccessReviewReadiness():array{return ['open'=>SecurityAccessReviewCycle::where('status','open')->count(),'overdue'=>SecurityAccessReviewCycle::where('status','open')->where('due_at','<',now())->count(),'completed'=>SecurityAccessReviewCycle::where('status','completed')->count()];}
 private function permit(User $a,string $p):void{if(!$a->can($p))throw ValidationException::withMessages(['permission'=>'Security access review permission is required.']);}private function event($c,$i,$a,$t,$d):void{SecurityAccessReviewEvent::create(['security_access_review_cycle_id'=>$c->id,'security_access_review_item_id'=>$i?->id,'actor_id'=>$a->id,'event_type'=>$t,'description'=>$d,'created_at'=>now()]);}
}
