<?php
namespace App\Services\Security;
use App\Models\{SecurityReviewerAccess,User};use Carbon\Carbon;use Illuminate\Validation\ValidationException;
class SecurityReviewerAccessService {
 public function grantAccess(User $user,string $scope,User $actor,array $data=[]):SecurityReviewerAccess{$access=SecurityReviewerAccess::withTrashed()->firstOrNew(['user_id'=>$user->id,'access_scope'=>$scope]);if($access->exists&&$access->trashed())$access->restore();$access->fill(['user_id'=>$user->id,'access_scope'=>$scope,'status'=>'active','source'=>$data['source']??'manual_admin','reason'=>$data['reason']??null,'granted_by_id'=>$actor->id,'granted_at'=>now(),'expires_at'=>$data['expires_at']??now()->addDays(7),'revoked_by_id'=>null,'revoked_at'=>null,'revocation_reason'=>null])->save();$this->event($access,$actor,'granted',$data['reason']??'Reviewer access granted.');return $access->refresh();}
 public function revokeAccess(SecurityReviewerAccess $access,User $actor,string $reason):SecurityReviewerAccess{if(blank($reason))throw ValidationException::withMessages(['reason'=>'Revocation reason is required.']);$access->update(['status'=>'revoked','revoked_by_id'=>$actor->id,'revoked_at'=>now(),'revocation_reason'=>$reason]);$this->event($access,$actor,'revoked',$reason);return $access->refresh();}
 public function extendAccess(SecurityReviewerAccess $access,User $actor,Carbon $expiresAt,string $reason):SecurityReviewerAccess{$access->update(['status'=>'active','expires_at'=>$expiresAt,'reason'=>$reason]);$this->event($access,$actor,'extended',$reason);return $access->refresh();}
 public function suspendAccess(SecurityReviewerAccess $access,User $actor,string $reason):SecurityReviewerAccess{$access->update(['status'=>'suspended','reason'=>$reason]);$this->event($access,$actor,'suspended',$reason);return $access->refresh();}
 public function expireDueAccesses():int{$count=0;SecurityReviewerAccess::where('status','active')->where('expires_at','<=',now())->each(function($a)use(&$count){$a->update(['status'=>'expired']);$this->event($a,null,'expired','Reviewer access expired.');$count++;});return $count;}
 public function canActAsReviewer(User $user,string $scope):array{if($user->hasAnyRole(['owner','admin']))return ['allowed'=>true,'reason'=>null];$a=SecurityReviewerAccess::where('user_id',$user->id)->where('access_scope',$scope)->first();$allowed=$a&&$a->status==='active'&&(!$a->expires_at||$a->expires_at->isFuture());return ['allowed'=>$allowed,'reason'=>$allowed?null:'Reviewer access is not active for retention approval.','access'=>$a];}
 public function getSensitiveAccessSummary():array{return ['active'=>SecurityReviewerAccess::where('status','active')->count(),'expiring_soon'=>SecurityReviewerAccess::where('status','active')->whereBetween('expires_at',[now(),now()->addDays(7)])->count(),'revoked'=>SecurityReviewerAccess::whereIn('status',['revoked','suspended','expired'])->count()];}
 private function event($a,?User $actor,$type,$description):void{$a->events()->create(['user_id'=>$a->user_id,'actor_id'=>$actor?->id,'event_type'=>$type,'description'=>$description,'created_at'=>now()]);}
}
