<?php
namespace App\Services\Security;
use App\Models\{EvidenceRetentionJob,EvidenceRetentionJobEvent,SecurityAccessReviewCycle,SecurityAccessReviewEvent,SecurityAuditExport,SecurityGovernanceNotification,SecurityReviewerAccess,SecurityReviewerAccessEvent,User,WorkerPayoutReviewEvidenceEvent};use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Symfony\Component\HttpFoundation\StreamedResponse;
class SecurityAuditExportService {
 public function generateSecurityGovernanceExport(User $actor,array $filters=[]):SecurityAuditExport{$number='SAE-'.now()->format('Ymd').'-'.Str::upper(Str::random(6));$payload=['generated_at'=>now()->toIso8601String(),'external_notifications_sent'=>false,'reviewer_accesses'=>SecurityReviewerAccess::get(['id','user_id','status','access_scope','source','granted_at','expires_at','revoked_at','revocation_reason']),'reviewer_access_events'=>SecurityReviewerAccessEvent::get(['security_reviewer_access_id','user_id','actor_id','event_type','description','created_at']),'access_review_cycles'=>SecurityAccessReviewCycle::with('items')->get(),'access_review_events'=>SecurityAccessReviewEvent::get(),'retention_jobs'=>EvidenceRetentionJob::with('items')->get(['id','job_number','status','mode','candidate_count','deleted_count','failed_count','cutoff_date','requested_by_id','approved_by_id','executed_by_id','requested_at','approved_at','executed_at']),'retention_events'=>EvidenceRetentionJobEvent::get(),'evidence_events'=>WorkerPayoutReviewEvidenceEvent::whereIn('event_type',['download_override_used','scan_unavailable','rescan_unavailable','downloaded'])->get(['evidence_id','worker_payout_review_id','actor_id','event_type','description','created_at']),'governance_notifications'=>SecurityGovernanceNotification::with('events')->get()];$json=json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);$path='security-audit-exports/'.now()->format('Y/m').'/'.$number.'.json';Storage::disk('local')->put($path,$json);$e=SecurityAuditExport::create(['export_number'=>$number,'export_type'=>'security_governance','status'=>'generated','format'=>'json','file_disk'=>'local','file_path'=>$path,'sha256_hash'=>hash('sha256',$json),'generated_by_id'=>$actor->id,'generated_at'=>now(),'filters'=>$filters,'record_counts'=>collect($payload)->map(fn($x)=>is_countable($x)?count($x):1)->all()]);$this->event($e,$actor,'generated','Private hash-stamped governance export generated.');return $e;}
 public function downloadExport(SecurityAuditExport $e,User $a):StreamedResponse{$this->event($e,$a,'downloaded','Private governance export downloaded.');return Storage::disk($e->file_disk)->download($e->file_path,$e->export_number.'.json');}
 public function archiveExport(SecurityAuditExport $e,User $a,string $reason):SecurityAuditExport{$e->update(['status'=>'archived']);$this->event($e,$a,'archived',$reason);return $e->refresh();}
 private function event($e,$a,$t,$d):void{$e->events()->create(['actor_id'=>$a->id,'event_type'=>$t,'description'=>$d,'created_at'=>now()]);}
}
