<?php
namespace App\Services\Security;
use App\Models\{EvidenceRetentionJob,EvidenceRetentionJobEvent,SecurityAccessReviewCycle,SecurityAccessReviewEvent,SecurityAuditExport,SecurityGovernanceNotification,SecurityReviewerAccess,SecurityReviewerAccessEvent,User,WorkerPayoutReviewEvidenceEvent};use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;use Symfony\Component\HttpFoundation\StreamedResponse;
class SecurityAuditExportService {
 public function generateSecurityGovernanceExport(User $actor,array $filters=[]):SecurityAuditExport{$number='SAE-'.now()->format('Ymd').'-'.Str::upper(Str::random(6));$payload=['generated_at'=>now()->toIso8601String(),'external_notifications_sent'=>false,'reviewer_accesses'=>SecurityReviewerAccess::get(['id','user_id','status','access_scope','source','granted_at','expires_at','revoked_at','revocation_reason']),'reviewer_access_events'=>SecurityReviewerAccessEvent::get(['security_reviewer_access_id','user_id','actor_id','event_type','description','created_at']),'access_review_cycles'=>SecurityAccessReviewCycle::with('items')->get(),'access_review_events'=>SecurityAccessReviewEvent::get(),'retention_jobs'=>EvidenceRetentionJob::with('items')->get(['id','job_number','status','mode','candidate_count','deleted_count','failed_count','cutoff_date','requested_by_id','approved_by_id','executed_by_id','requested_at','approved_at','executed_at']),'retention_events'=>EvidenceRetentionJobEvent::get(),'evidence_events'=>WorkerPayoutReviewEvidenceEvent::whereIn('event_type',['download_override_used','scan_unavailable','rescan_unavailable','downloaded'])->get(['evidence_id','worker_payout_review_id','actor_id','event_type','description','created_at']),'governance_notifications'=>SecurityGovernanceNotification::with('events')->get()];$json=json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);$path='security-audit-exports/'.now()->format('Y/m').'/'.$number.'.json';Storage::disk('local')->put($path,$json);$e=SecurityAuditExport::create(['export_number'=>$number,'export_type'=>'security_governance','status'=>'generated','format'=>'json','file_disk'=>'local','file_path'=>$path,'sha256_hash'=>hash('sha256',$json),'generated_by_id'=>$actor->id,'generated_at'=>now(),'filters'=>$filters,'record_counts'=>collect($payload)->map(fn($x)=>is_countable($x)?count($x):1)->all()]);$this->event($e,$actor,'generated','Private hash-stamped governance export generated.');return $e;}
 public function downloadExport(SecurityAuditExport $e,User $a):StreamedResponse{if(!$a->can('admin.security.audit_exports.download')){$this->event($e,$a,'unauthorized_download_blocked','Audit export download permission is required.');throw ValidationException::withMessages(['permission'=>'Audit export download permission is required.']);}if($e->status!=='generated'){$this->event($e,$a,'download_blocked','Only generated exports may be downloaded.');throw ValidationException::withMessages(['status'=>'Only generated exports may be downloaded.']);}if(!Storage::disk($e->file_disk)->exists($e->file_path))throw ValidationException::withMessages(['file'=>'Private export file is unavailable.']);$hash=hash_file('sha256',Storage::disk($e->file_disk)->path($e->file_path));if(!hash_equals((string)$e->sha256_hash,$hash)){$this->event($e,$a,'failed','Audit export hash mismatch.');throw ValidationException::withMessages(['hash'=>'Audit export integrity check failed.']);}$e->increment('download_count');$e->update(['last_downloaded_at'=>now(),'last_downloaded_by_id'=>$a->id]);$this->event($e,$a,'downloaded','Private governance export downloaded after SHA-256 verification.');return Storage::disk($e->file_disk)->download($e->file_path,$e->export_number.'.json');}
 public function archiveExport(SecurityAuditExport $e,User $a,string $reason):SecurityAuditExport{if(!$a->can('admin.security.audit_exports.archive')||blank($reason))throw ValidationException::withMessages(['archive'=>'Archive permission and reason are required.']);$e->update(['status'=>'archived','archived_at'=>now(),'archived_by_id'=>$a->id,'archive_reason'=>$reason]);$this->event($e,$a,'archived',$reason);return $e->refresh();}
 public function scheduleRetention(SecurityAuditExport $e,User $a,\Carbon\Carbon $until,string $reason):SecurityAuditExport{if(!$a->can('admin.security.audit_exports.archive')||blank($reason))throw ValidationException::withMessages(['retention'=>'Retention permission and reason are required.']);$e->update(['retention_until'=>$until]);$this->event($e,$a,'retention_scheduled',$reason);return $e->refresh();}
 private function event($e,$a,$t,$d):void{$e->events()->create(['actor_id'=>$a->id,'event_type'=>$t,'description'=>$d,'created_at'=>now()]);}
}
