<?php
return [
'admin'=>['dashboard'=>'Kontrollpanel','operations'=>'Operasjoner','dispatch'=>'Disponering','orders'=>'Bestillinger','people'=>'Personell','services'=>'Tjenester','finance'=>'Økonomi','support'=>'Kundestøtte','content'=>'Innhold','system'=>'System'],
'modules'=>['operations'=>'Operasjonssentral','dispatch'=>'Disponeringssenter','live_map'=>'Live operasjonskart','orders'=>'Bestillingssenter','people'=>'Personell og arbeidsstyrke','services'=>'Tjenestekatalog','finance'=>'Økonomistyring','support'=>'Kundestøttesenter','content'=>'CMS og SEO','system'=>'System og sikkerhet','translations'=>'Oversettelsesbehandling'],
'descriptions'=>['operations'=>'Operativ beredskap og kontroll','dispatch'=>'Tildeling og disponering','live_map'=>'Kun ekte GPS-signaler fra arbeidere','orders'=>'Livssyklus og handlingskø for bestillinger','people'=>'Arbeidere, søknader og etterlevelse','services'=>'Tjenestescenarier og inntaksfelt','finance'=>'Prising og betalingsberedskap','support'=>'Saker og operative hendelser','content'=>'Offentlig innhold og SEO','system'=>'Sikkerhet, innstillinger og revisjon','translations'=>'Administrer oversettelser for admin og produkt'],
'common'=>['module_switcher'=>'Modulvelger for BiKuBe Admin OS','status'=>'Status','action'=>'Handling','actions'=>'Handlinger','save'=>'Lagre','edit'=>'Rediger','open'=>'Åpne','download'=>'Last ned','approve'=>'Godkjenn','reject'=>'Avvis','pending'=>'Venter','approved'=>'Godkjent','rejected'=>'Avvist','expired'=>'Utløpt','not_connected'=>'Ikke tilkoblet','not_exposed'=>'Ikke eksponert','no_data'=>'Ingen data','back_to_admin'=>'Tilbake til Admin OS','open_real_route'=>'Åpne faktisk rute'],
'documents'=>['title'=>'Arbeiderdokumenter','document_type'=>'Dokumenttype','required'=>'Påkrevd','compliance_status'=>'Etterlevelsesstatus','risk_level'=>'Risikonivå','evidence'=>'Dokumentasjon','manually_verified'=>'Manuelt verifisert','expires_at'=>'Utløper','missing_evidence'=>'Mangler dokumentasjon','ready_for_review'=>'Klar for kontroll','private_download'=>'Privat revidert nedlasting','verification_note'=>'Verifikasjonsnotat','rejection_reason'=>'Årsak til avvisning'],
'settings'=>['platform'=>'Plattforminnstillinger','operations'=>'Operasjonsinnstillinger','map'=>'Kartinnstillinger','payment_disabled'=>'Betalingsleverandør er ikke tilkoblet ennå.','tracking_disabled'=>'Kundesporing er ikke eksponert ennå.'],
'system_security'=>['title'=>'System og sikkerhet','back_to_admin'=>'Tilbake til Admin OS','kicker'=>'BiKuBe Next / System','description'=>'Faktisk status for kjøretid, sikkerhet og pakker.','operational_modules'=>'Operative moduler','installed_foundation_status'=>'Status for installert grunnlag','security_foundation'=>'Sikkerhetsgrunnlag','auth_rbac_audit'=>'Autentisering, RBAC og revisjon','security_checklist'=>'Sikkerhetssjekkliste'],
'localization'=>['choose_language'=>'Velg språk','title'=>'Oversettelsesbehandling','coverage'=>'Oversettelsesdekning','missing'=>'Manglende oversettelser','fallback'=>'Reservespråk'],
'status'=>['blocked'=>'Blokkert','ready'=>'Klar','pending'=>'Venter','completed'=>'Fullført','verified'=>'Verifisert','recurring'=>'Gjentakende'],
'blockers'=>['payment_not_captured'=>'Betalingen er ikke registrert.','payout_provider_not_configured'=>'Utbetalingsleverandør er ikke konfigurert.','settlement_rule_not_active'=>'Oppgjørsregelen er ikke aktiv.','worker_payout_profile_not_approved'=>'Utførerens utbetalingsprofil er ikke godkjent.','scanner_disabled'=>'Skanneren er deaktivert.','malware_scanning_not_configured'=>'Skanning etter skadevare er ikke konfigurert.','reviewer_access_not_active'=>'Kontrollørtilgangen er ikke aktiv.','audit_export_download_permission_required'=>'Tillatelse til å laste ned revisjonseksport kreves.','customer_completion_required'=>'Kundens bekreftelse på fullføring kreves.','private_document_policy_required'=>'Privat dokumentopplasting krever godkjent sikkerhetspolicy for medier.'],
];
