<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('payment_records',function(Blueprint $t){$t->id();$t->string('payment_number')->unique();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('customer_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('billing_document_id')->nullable()->constrained()->nullOnDelete();$t->string('provider')->default('disabled')->index();$t->string('provider_reference')->nullable();$t->string('status')->default('draft')->index();$t->string('currency',3)->default('NOK');$t->decimal('amount',12,2)->nullable();$t->string('idempotency_key')->nullable()->unique();$t->foreignId('requested_by_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('captured_by_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('refunded_by_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('authorized_at')->nullable();$t->timestamp('captured_at')->nullable();$t->timestamp('refunded_at')->nullable();$t->timestamp('failed_at')->nullable();$t->text('failure_reason')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->softDeletes();});
  Schema::create('payment_events',function(Blueprint $t){$t->id();$t->foreignId('payment_record_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('actor_id')->nullable()->constrained('users')->nullOnDelete();$t->string('event_type')->index();$t->string('provider')->nullable();$t->string('provider_reference')->nullable();$t->string('idempotency_key')->nullable();$t->text('description')->nullable();$t->string('payload_hash')->nullable();$t->json('metadata')->nullable();$t->timestamp('created_at');});
  Schema::create('payment_webhook_events',function(Blueprint $t){$t->id();$t->string('provider')->index();$t->string('provider_event_id')->nullable();$t->string('event_type')->nullable();$t->string('payload_hash')->index();$t->string('status')->default('received')->index();$t->foreignId('related_payment_record_id')->nullable()->constrained('payment_records')->nullOnDelete();$t->timestamp('received_at');$t->timestamp('processed_at')->nullable();$t->text('failure_reason')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['provider','provider_event_id']);});
 }
 public function down():void{Schema::dropIfExists('payment_webhook_events');Schema::dropIfExists('payment_events');Schema::dropIfExists('payment_records');}
};
