<?php

return [
    'admin_modules' => [
        'operations' => [
            'label' => 'Operations Command Center',
            'status' => 'readiness cockpit active',
            'purpose' => 'Owner/admin cockpit for health, launch gates, SLA, incidents, and operational readiness.',
            'owning_context' => 'Operations',
            'safe_actions' => ['Read module readiness once real projections exist.'],
            'blocked_actions' => ['No fake KPIs, no fake live status, no production controls until services exist.'],
            'next_steps' => ['Define operations projections.', 'Wire real health and queue metrics.', 'Add launch-readiness gate checks.'],
        ],
        'dispatch' => [
            'label' => 'Dispatch Center',
            'status' => 'not connected',
            'purpose' => 'Assignment, reassignment, SLA risk, and operational override with audit trail.',
            'owning_context' => 'Dispatch Engine',
            'safe_actions' => ['Read dispatch queue once Order and Worker modules exist.'],
            'blocked_actions' => ['No fake courier assignment.', 'No direct DB writes.', 'No route markers without real coordinates.'],
            'next_steps' => ['Define dispatch aggregate.', 'Define worker availability contract.', 'Create assignment service interface.'],
        ],
        'orders' => [
            'label' => 'Orders Hub',
            'status' => 'order and intake engines active',
            'purpose' => 'Central order operations for every service scenario and lifecycle event.',
            'owning_context' => 'Order Engine',
            'safe_actions' => ['No action yet.'],
            'blocked_actions' => ['No fake order success.', 'No payment status mutation without Payment Engine.'],
            'next_steps' => ['Create Order aggregate design.', 'Define lifecycle state machine.', 'Define order event model.'],
        ],
        'people' => [
            'label' => 'People & Workforce',
            'status' => 'RBAC foundation only',
            'purpose' => 'Users, customers, workers, partners, support and finance operator management.',
            'owning_context' => 'Identity & RBAC',
            'safe_actions' => ['Use Filament Shield after policy design.'],
            'blocked_actions' => ['No fake workers.', 'No bypassed approval/onboarding.'],
            'next_steps' => ['Define role taxonomy.', 'Define worker onboarding gates.', 'Define device/session model.'],
        ],
        'services' => [
            'label' => 'Service Catalog',
            'status' => 'scenario engine active',
            'purpose' => 'Service scenarios, form rules, launch visibility, pricing inputs and compliance boundaries.',
            'owning_context' => 'Service Scenario Engine',
            'safe_actions' => ['Read scenario registry once implemented.'],
            'blocked_actions' => ['No regulated care claims without legal review.', 'No checkout bypass.'],
            'next_steps' => ['Create scenario registry.', 'Define 9 launch modules.', 'Separate launch-visible from hidden services.'],
        ],
        'finance' => [
            'label' => 'Finance Control',
            'status' => 'pricing active; provider not connected',
            'purpose' => 'Payments, refunds, wallet ledger, payout batches, partner settlements, and invoices.',
            'owning_context' => 'Payment Engine + Wallet',
            'safe_actions' => ['Read manual/local status only once payment model exists.'],
            'blocked_actions' => ['No fake paid status.', 'No fake payouts.', 'No provider credential changes.'],
            'next_steps' => ['Design payment attempts and webhook idempotency.', 'Design ledger.', 'Define Vipps/MobilePay adapter boundary.'],
        ],
        'support' => [
            'label' => 'Support Center',
            'status' => 'not implemented',
            'purpose' => 'Customer, worker, partner and payment support tickets with order context and escalation.',
            'owning_context' => 'Support / Chat',
            'safe_actions' => ['No action yet.'],
            'blocked_actions' => ['No fake chat.', 'No external contact from admin skeleton.'],
            'next_steps' => ['Define ticket aggregate.', 'Define message thread.', 'Define SLA and escalation rules.'],
        ],
        'content' => [
            'label' => 'CMS & SEO',
            'status' => 'CMS foundation active',
            'purpose' => 'Landing pages, service pages, SEO metadata, translations, sitemap and legal content.',
            'owning_context' => 'CMS / SEO',
            'safe_actions' => ['Spatie sitemap is installed for later implementation.'],
            'blocked_actions' => ['No Elfsight operational widgets.', 'No external marketing widgets in core flow.'],
            'next_steps' => ['Define page model.', 'Define SEO metadata contract.', 'Define multilingual slug strategy.'],
        ],
        'system' => [
            'label' => 'System & Security',
            'status' => 'operational tooling wired',
            'purpose' => 'Audit, feature flags, webhooks, API security, observability, backups and platform settings.',
            'owning_context' => 'Security / Audit / DevOps',
            'safe_actions' => ['Pennant, Pulse, Horizon, Telescope and Activitylog are installed for later wiring.'],
            'blocked_actions' => ['No secrets in UI.', 'No production service changes from skeleton.'],
            'next_steps' => ['Define audit events.', 'Define feature flags.', 'Define health checks and webhook signature policy.'],
        ],
    ],

    'service_modules' => [
        'delivery.groceries',
        'delivery.meals',
        'delivery.bulky',
        'moving.home',
        'moving.business',
        'eco.disposal',
        'eco.furniture',
        'eco.appliances',
        'handyman.hourly',
        'handyman.assembly',
        'handyman.repair',
        'tow.emergency',
        'roadside.assistance',
        'personal-task.errand',
        'personal-task.concierge',
        'classifieds.delivery',
    ],
];
