@php($proof=$this->getProof()) @php($a=$proof['action']??[])
<x-filament-panels::page><main class="bkb-admin-shell bkb-operator">
<header class="bkb-operator-head"><div><p class="bkb-kicker">{{ __('bikube.dashboard.kicker') }}</p><h1>{{ __('bikube.dashboard.title') }}</h1><p>{{ __('bikube.dashboard.description') }}</p></div><span class="bkb-status-badge">{{ __('bikube.dashboard.payment_provider_not_connected') }}</span></header>
<section class="bkb-foundation-strip">@foreach(['orders_needing_action'=>'orders_needing_action','unassigned'=>'unassigned','dispatch_ready'=>'dispatch_ready','applications'=>'applications','documents'=>'documents_pending','eligible_workers'=>'eligible_workers'] as $k=>$l)<article><span>{{ __('bikube.dashboard.'.$l) }}</span><strong>{{$a[$k]??0}}</strong></article>@endforeach</section>
<section class="bkb-operator-grid"><article class="bkb-os-card"><h2>{{ __('bikube.dashboard.next_operational_action') }}</h2><dl class="bkb-module-meta"><div><dt>{{ __('bikube.dashboard.latest_order') }}</dt><dd>{{$a['latest_order']??__('bikube.common.no_data')}}</dd></div><div><dt>{{ __('bikube.dashboard.latest_application') }}</dt><dd>{{$a['latest_application']??__('bikube.common.no_data')}}</dd></div><div><dt>{{ __('bikube.dashboard.assignment_blocker') }}</dt><dd>{{($a['eligible_workers']??0)>0?__('bikube.dashboard.eligible_worker_available'):__('bikube.dashboard.no_eligible_worker')}}</dd></div></dl></article>
<article class="bkb-os-card"><h2>{{ __('bikube.common.actions') }}</h2><nav class="bkb-action-list"><a href="{{route('filament.admin.pages.dispatch-center')}}">{{ __('bikube.dashboard.open_dispatch_queue') }}</a><a href="{{\App\Filament\Resources\WorkerApplications\WorkerApplicationResource::getUrl()}}">{{ __('bikube.dashboard.review_worker_applications') }}</a><a href="{{\App\Filament\Resources\WorkerDocuments\WorkerDocumentResource::getUrl()}}">{{ __('bikube.dashboard.review_worker_documents') }}</a><a href="{{\App\Filament\Resources\Orders\OrderResource::getUrl()}}">{{ __('bikube.dashboard.open_orders') }}</a><a href="{{\App\Filament\Resources\PricingRules\PricingRuleResource::getUrl()}}">{{ __('bikube.dashboard.open_pricing_rules') }}</a></nav></article></section>
<section class="bkb-table-wrap"><h2>{{ __('bikube.dashboard.action_required_now') }}</h2><table class="bkb-ops-table"><tbody><tr><td>{{ __('bikube.dashboard.review_worker_applications') }}</td><td>{{$a['applications']??0}}</td><td>{{($a['applications']??0)?__('bikube.dashboard.open_queue'):__('bikube.dashboard.no_submitted_applications')}}</td></tr><tr><td>{{ __('bikube.dashboard.review_documents') }}</td><td>{{$a['documents']??0}}</td><td>{{($a['documents']??0)?__('bikube.dashboard.open_queue'):__('bikube.dashboard.no_pending_documents')}}</td></tr><tr><td>{{ __('bikube.dashboard.mark_dispatch_ready') }}</td><td>{{$a['unassigned']??0}}</td><td>{{ __('bikube.dashboard.open_dispatch_queue') }}</td></tr><tr><td>{{ __('bikube.dashboard.assign_eligible_worker') }}</td><td>{{$a['eligible_workers']??0}}</td><td>{{($a['eligible_workers']??0)?__('bikube.dashboard.worker_available'):__('bikube.dashboard.blocked_no_eligible_worker')}}</td></tr><tr><td>{{ __('bikube.dashboard.review_manual_quote') }}</td><td>{{$proof['pricing']['manual']??0}}</td><td>{{ __('bikube.dashboard.open_finance_control') }}</td></tr></tbody></table></section>
<section class="bkb-honesty-panel"><div><span>{{ __('bikube.dashboard.unavailable_modules') }}</span><strong>{{ __('bikube.dashboard.unavailable_modules_list') }}</strong></div><p>{{ __('bikube.dashboard.unavailable_modules_detail') }}</p></section>
</main></x-filament-panels::page>
