@php($proof=$this->getProof()) @php($a=$proof['action']??[])
<x-filament-panels::page><main class="bkb-admin-shell bkb-operator">
<header class="bkb-operator-head"><div><p class="bkb-kicker">Narvik operations</p><h1>Operator overview</h1><p>Real queues and current blockers.</p></div><span class="bkb-status-badge">Payment provider: not connected</span></header>
<section class="bkb-foundation-strip">@foreach(['orders_needing_action'=>'Orders needing action','unassigned'=>'Unassigned','dispatch_ready'=>'Dispatch ready','applications'=>'Applications','documents'=>'Documents pending','eligible_workers'=>'Eligible workers'] as $k=>$l)<article><span>{{$l}}</span><strong>{{$a[$k]??0}}</strong></article>@endforeach</section>
<section class="bkb-operator-grid"><article class="bkb-os-card"><h2>Next operational action</h2><dl class="bkb-module-meta"><div><dt>Latest order</dt><dd>{{$a['latest_order']??'None'}}</dd></div><div><dt>Latest application</dt><dd>{{$a['latest_application']??'None'}}</dd></div><div><dt>Assignment blocker</dt><dd>{{($a['eligible_workers']??0)>0?'Eligible worker available':'No approved online capability-matched worker'}}</dd></div></dl></article>
<article class="bkb-os-card"><h2>Actions</h2><nav class="bkb-action-list"><a href="{{route('filament.admin.pages.dispatch-center')}}">Open Dispatch Queue</a><a href="{{\App\Filament\Resources\WorkerApplications\WorkerApplicationResource::getUrl()}}">Review Worker Applications</a><a href="{{\App\Filament\Resources\WorkerDocuments\WorkerDocumentResource::getUrl()}}">Review Worker Documents</a><a href="{{\App\Filament\Resources\Orders\OrderResource::getUrl()}}">Open Orders</a><a href="{{\App\Filament\Resources\PricingRules\PricingRuleResource::getUrl()}}">Open Pricing Rules</a></nav></article></section>
<section class="bkb-table-wrap"><h2>Action required now</h2><table class="bkb-ops-table"><tbody><tr><td>Review worker applications</td><td>{{$a['applications']??0}}</td><td>{{($a['applications']??0)?'Open queue':'No submitted applications'}}</td></tr><tr><td>Review documents</td><td>{{$a['documents']??0}}</td><td>{{($a['documents']??0)?'Open queue':'No pending documents'}}</td></tr><tr><td>Mark dispatch ready</td><td>{{$a['unassigned']??0}}</td><td>Open Dispatch Queue</td></tr><tr><td>Assign eligible worker</td><td>{{$a['eligible_workers']??0}}</td><td>{{($a['eligible_workers']??0)?'Worker available':'Blocked: no eligible worker'}}</td></tr><tr><td>Review manual quote</td><td>{{$proof['pricing']['manual']??0}}</td><td>Open Finance Control</td></tr></tbody></table></section>
<section class="bkb-honesty-panel"><div><span>Unavailable modules</span><strong>Payment provider · GPS · live map</strong></div><p>These capabilities are not exposed as working actions.</p></section>
</main></x-filament-panels::page>
