<x-filament-panels::page><x-admin-os.module-shell class="los" label="Service Zones Manager">
<header class="los-head"><div><span class="los-label">LiveOps Suite</span><h1>Service Zones</h1><p>Persisted operational geofences, lifecycle events and map context.</p></div><x-admin-os.liveops-nav /></header>
<section class="los-kpis">@foreach(['total'=>'Total zones','active'=>'Active','no_go'=>'Active no-go','events'=>'Zone events'] as $k=>$l)<article class="los-kpi"><span>{{ $l }}</span><strong>{{ $metrics[$k] }}</strong></article>@endforeach</section>
<div class="los-grid">
<section class="los-panel"><header><h2>Zone registry</h2><b>{{ $zones->count() }}</b></header><div class="los-list">@forelse($zones as $z)<button class="los-row {{ $selectedZone?->is($z)?'is-active':'' }}" wire:click="selectZone({{$z->id}})"><strong>{{$z->name}}</strong><span>{{str($z->type)->replace('_',' ')->title()}} · {{$z->status}} · {{$z->radius_meters ? $z->radius_meters.' m':'point'}}</span></button>@empty<div class="los-empty">No persisted zones.</div>@endforelse</div></section>
<section class="los-panel"><header><h2>Zone map</h2><a class="los-action" href="{{route('filament.admin.pages.live-operations-map')}}">Open Fleet Map</a></header><div id="zones-map" class="los-map"></div><p class="los-empty">Circle and point zones are supported. Polygon drawing requires an approved drawing plugin.</p></section>
<aside class="los-panel"><header><h2>{{ $selectedZone?->name ?? 'Create zone' }}</h2></header>
<form class="los-form" wire:submit="createZone"><label>Name<input wire:model="name" required></label><label>Type<select wire:model="type">@foreach(['service_area','priority_area','no_go_area','temporary_busy_area','pickup_hotspot','support_incident'] as $t)<option value="{{$t}}">{{str($t)->replace('_',' ')->title()}}</option>@endforeach</select></label><label>Latitude<input wire:model="latitude" type="number" step=".0000001"></label><label>Longitude<input wire:model="longitude" type="number" step=".0000001"></label><label>Radius meters<input wire:model="radius" type="number"></label><label>Note<textarea wire:model="note"></textarea></label><button>Create real zone</button>@if($selectedZone)<button type="button" wire:click="updateZone">Update selected</button><button type="button" wire:click="addNote">Add note</button><label>Deactivate reason<input wire:model="reason"></label><button type="button" wire:click="deactivateZone">Deactivate</button>@endif</form>
@if($selectedZone)<div class="los-list">@foreach($selectedZone->events as $e)<article class="los-row"><strong>{{str($e->event_type)->replace('_',' ')->title()}}</strong><span>{{$e->description}} · {{$e->created_at?->diffForHumans()}}</span></article>@endforeach</div>@endif</aside>
</div></x-admin-os.module-shell>
@push('styles')<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">@endpush
@push('scripts')<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const m=L.map('zones-map').setView([68.4385,17.4272],10);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(m);@foreach($zones->where('status','active') as $z) L.circle([{{$z->coordinates['lat']}},{{$z->coordinates['lng']}}],{radius:{{$z->radius_meters??30}},color:@json($z->color)}).addTo(m).bindPopup(@json($z->name));@endforeach})</script>@endpush
</x-filament-panels::page>
