<?php
return [
'admin'=>['dashboard'=>'Панель','operations'=>'Операції','dispatch'=>'Диспетчерська','orders'=>'Замовлення','people'=>'Персонал','services'=>'Послуги','finance'=>'Фінанси','support'=>'Підтримка','content'=>'Контент','system'=>'Система'],
'modules'=>['operations'=>'Операційний центр','dispatch'=>'Диспетчерський центр','live_map'=>'Карта операцій','orders'=>'Центр замовлень','people'=>'Персонал і виконавці','services'=>'Каталог послуг','finance'=>'Фінансовий контроль','support'=>'Центр підтримки','content'=>'CMS і SEO','system'=>'Система і безпека','translations'=>'Менеджер перекладів'],
'descriptions'=>['operations'=>'Контроль операційної готовності','dispatch'=>'Призначення та диспетчерські операції','live_map'=>'Лише реальні GPS-сигнали виконавців','orders'=>'Життєвий цикл і черга дій замовлень','people'=>'Виконавці, заявки та комплаєнс','services'=>'Сценарії послуг і поля заявки','finance'=>'Ціноутворення та готовність платежів','support'=>'Тікети й операційні інциденти','content'=>'Публічний контент і SEO','system'=>'Безпека, налаштування та аудит','translations'=>'Керування перекладами адмінки та продукту'],
'common'=>['module_switcher'=>'Перемикач модулів BiKuBe Admin OS','status'=>'Статус','action'=>'Дія','actions'=>'Дії','save'=>'Зберегти','edit'=>'Змінити','open'=>'Відкрити','download'=>'Завантажити','approve'=>'Схвалити','reject'=>'Відхилити','pending'=>'Очікує','approved'=>'Схвалено','rejected'=>'Відхилено','expired'=>'Прострочено','not_connected'=>'Не підключено','not_exposed'=>'Не оприлюднено','no_data'=>'Немає даних','back_to_admin'=>'Назад до Admin OS','open_real_route'=>'Відкрити робочий маршрут'],
'documents'=>['title'=>'Документи виконавців','document_type'=>'Тип документа','required'=>'Обов’язковий','compliance_status'=>'Статус комплаєнсу','risk_level'=>'Рівень ризику','evidence'=>'Підтвердження','manually_verified'=>'Перевірено вручну','expires_at'=>'Термін дії','missing_evidence'=>'Немає підтвердження','ready_for_review'=>'Готово до перевірки','private_download'=>'Приватне завантаження з аудитом','verification_note'=>'Примітка перевірки','rejection_reason'=>'Причина відхилення'],
'settings'=>['platform'=>'Налаштування платформи','operations'=>'Налаштування операцій','map'=>'Налаштування карти','payment_disabled'=>'Платіжний провайдер ще не підключено.','tracking_disabled'=>'Відстеження для клієнта ще не оприлюднено.'],
'system_security'=>['title'=>'Система і безпека','back_to_admin'=>'Назад до Admin OS','kicker'=>'BiKuBe Next / Система','description'=>'Реальний статус середовища, безпеки та пакетів.','operational_modules'=>'Операційні модулі','installed_foundation_status'=>'Статус встановленої основи','security_foundation'=>'Основа безпеки','auth_rbac_audit'=>'Авторизація, RBAC та аудит','security_checklist'=>'Чекліст безпеки'],
'localization'=>['choose_language'=>'Оберіть мову','title'=>'Менеджер перекладів','coverage'=>'Покриття перекладу','missing'=>'Відсутні переклади','fallback'=>'Резервна мова'],
'status'=>['blocked'=>'Заблоковано','ready'=>'Готово','pending'=>'Очікує','completed'=>'Завершено','verified'=>'Перевірено','recurring'=>'Повторюється'],
'blockers'=>['payment_not_captured'=>'Платіж не отримано.','payout_provider_not_configured'=>'Провайдера виплат не налаштовано.','settlement_rule_not_active'=>'Правило розрахунку не активне.','worker_payout_profile_not_approved'=>'Профіль виплат виконавця не схвалено.','scanner_disabled'=>'Сканер вимкнено.','malware_scanning_not_configured'=>'Сканування на шкідливе ПЗ не налаштовано.','reviewer_access_not_active'=>'Доступ перевіряльника не активний.','audit_export_download_permission_required'=>'Потрібен дозвіл на завантаження аудиторського експорту.','customer_completion_required'=>'Потрібне підтвердження виконання від клієнта.','private_document_policy_required'=>'Приватне завантаження документів потребує схваленої політики безпеки медіафайлів.'],
'dashboard'=>['kicker'=>'Операції в Нарвіку','title'=>'Огляд оператора','description'=>'Реальні черги та поточні блокування.','payment_provider_not_connected'=>'Платіжний провайдер: не підключено','orders_needing_action'=>'Замовлення, що потребують дій','unassigned'=>'Не призначено','dispatch_ready'=>'Готово до диспетчеризації','applications'=>'Заявки','documents_pending'=>'Документи на розгляді','eligible_workers'=>'Відповідні виконавці','next_operational_action'=>'Наступна операційна дія','latest_order'=>'Останнє замовлення','latest_application'=>'Остання заявка','assignment_blocker'=>'Причина блокування призначення','eligible_worker_available'=>'Доступний відповідний виконавець','no_eligible_worker'=>'Немає схваленого онлайн-виконавця з потрібними можливостями','open_dispatch_queue'=>'Відкрити чергу диспетчеризації','review_worker_applications'=>'Переглянути заявки виконавців','review_worker_documents'=>'Переглянути документи виконавців','open_orders'=>'Відкрити замовлення','open_pricing_rules'=>'Відкрити правила ціноутворення','action_required_now'=>'Потрібна дія зараз','open_queue'=>'Відкрити чергу','no_submitted_applications'=>'Немає поданих заявок','review_documents'=>'Переглянути документи','no_pending_documents'=>'Немає документів на розгляді','mark_dispatch_ready'=>'Позначити готовим до диспетчеризації','assign_eligible_worker'=>'Призначити відповідного виконавця','worker_available'=>'Виконавець доступний','blocked_no_eligible_worker'=>'Заблоковано: немає відповідного виконавця','review_manual_quote'=>'Переглянути ручну пропозицію','open_finance_control'=>'Відкрити фінансовий контроль','unavailable_modules'=>'Недоступні модулі','unavailable_modules_list'=>'Платіжний провайдер · GPS · жива мапа','unavailable_modules_detail'=>'Ці можливості не показуються як робочі дії.'],
'operations'=>['kicker'=>'BiKuBe Next / Операції','title'=>'Операційний центр','description'=>'Реальна панель готовності до запуску платформи в Нарвіку. Сторінка показує фактичний стан системи та не використовує вигадані операційні дані.','status_label'=>'Стан операцій','skeleton_foundation'=>'Базова структура','no_legacy_data'=>'Застарілі дані не підключено','no_fake_data'=>'Без фальшивих GPS, замовлень і платежів','foundation_summary'=>'Огляд базової готовності','operational_posture'=>'Операційна готовність','foundation_only'=>'Лише базова основа','foundation_only_detail'=>'Готово до реальних доменних модулів, але не до виробничої диспетчеризації.','launch_city'=>'Місто запуску','narvik_first'=>'Спочатку Нарвік','narvik_detail'=>'Норвезькі очікування та межі відповідності залишаються видимими.','data_policy'=>'Політика даних','honest_state'=>'Чесний стан','honest_state_detail'=>'Без умовних чисел, фальшивих черг і фальшивих карт.','runtime_evidence'=>'Дані середовища виконання','current_foundation_checks'=>'Поточні перевірки основи','installed_modules'=>'Встановлені операційні модулі','module_foundation_wiring'=>'Підключення базових модулів','readiness_gates'=>'Умови готовності','real_operations_blockers'=>'Що блокує реальні операції','operations_rail'=>'Операційна панель','admin_routes'=>'Сторінки Admin OS','route_map'=>'Мапа базових маршрутів','action_honesty'=>'Прозорість дій','action_classification'=>'Видима класифікація дій'],
'operational_states'=>['safe'=>'Безпечно','review'=>'Потребує перевірки'],
'admin_ui'=>[
'Actions'=>'Дії','Active'=>'Активно','Add'=>'Додати','Admin OS routes'=>'Сторінки Admin OS','All'=>'Усі','Amount'=>'Сума','Approved'=>'Схвалено','Archive'=>'Архівувати','Assigned'=>'Призначено','Blocked'=>'Заблоковано','Cancel'=>'Скасувати','Completed'=>'Завершено','Configuration'=>'Налаштування','Create'=>'Створити','Current status'=>'Поточний стан','Customer'=>'Клієнт','Dashboard'=>'Огляд','Date'=>'Дата','Delete'=>'Видалити','Description'=>'Опис','Disabled'=>'Вимкнено','Download'=>'Завантажити','Edit'=>'Редагувати','Email'=>'Електронна пошта','Enabled'=>'Увімкнено','Evidence'=>'Підтвердження','Export'=>'Експортувати','Finance'=>'Фінанси','Finance Control'=>'Фінансовий контроль','Name'=>'Назва','Next action'=>'Наступна дія','No data'=>'Немає даних','Open'=>'Відкрити','Operations'=>'Операції','Orders'=>'Замовлення','Orders Hub'=>'Центр замовлень','Owner'=>'Власник','Payment provider is not configured.'=>'Платіжного провайдера не налаштовано.','Payment is not captured.'=>'Платіж не отримано.','Pending'=>'Очікує','People'=>'Люди','Priority'=>'Пріоритет','Provider'=>'Провайдер','Ready'=>'Готово','Reason'=>'Причина','Reject'=>'Відхилити','Rejected'=>'Відхилено','Review'=>'Перевірка','Reviewer'=>'Перевіряльник','Save'=>'Зберегти','Security'=>'Безпека','Security Governance'=>'Керування безпекою','Service Catalog'=>'Каталог послуг','Services'=>'Послуги','Settings'=>'Налаштування','Status'=>'Статус','Submit'=>'Надіслати','Support'=>'Підтримка','Support Center'=>'Центр підтримки','System'=>'Система','System & Security'=>'Система і безпека','Tax review is not approved.'=>'Податкову перевірку не схвалено.','Translation Manager'=>'Менеджер перекладів','Unassigned'=>'Не призначено','Updated at'=>'Оновлено','User'=>'Користувач','View'=>'Переглянути','Worker'=>'Виконавець','Worker payout profile is not approved.'=>'Профіль виплат виконавця не схвалено.','Worker settlement rule is not configured.'=>'Правило розрахунку виконавця не налаштовано.',
],
];
