<?php
namespace App\Filament\Resources\SupportTickets;
use App\Filament\Resources\SupportTickets\Pages\{CreateSupportTicket,EditSupportTicket,ListSupportTickets,ViewSupportTicket};
use App\Models\SupportTicket; use App\Services\Support\SupportTicketService; use BackedEnum;
use Filament\Actions\{Action,EditAction,ViewAction}; use Filament\Forms\Components\{Select,SpatieMediaLibraryFileUpload,Textarea,TextInput}; use Filament\Resources\Resource; use Filament\Schemas\Components\Section; use Filament\Schemas\Components\View; use Filament\Schemas\Schema; use Filament\Support\Icons\Heroicon; use Filament\Tables\Columns\TextColumn; use Filament\Tables\Filters\{Filter,SelectFilter}; use Filament\Tables\Table; use Illuminate\Database\Eloquent\Builder;
class SupportTicketResource extends Resource {
 protected static ?string $model=SupportTicket::class; protected static string|BackedEnum|null $navigationIcon=Heroicon::OutlinedLifebuoy; protected static string|\UnitEnum|null $navigationGroup='Support'; protected static ?string $recordTitleAttribute='ticket_number';
 public static function canAccess():bool{return auth()->user()?->can('admin.support.view')??false;}
 public static function form(Schema $s):Schema{return $s->components([Section::make('Ticket')->columns(2)->schema([TextInput::make('ticket_number')->disabled()->dehydrated(false),TextInput::make('subject')->required(),Select::make('status')->options(self::statuses())->required(),Select::make('priority')->options(self::priorities())->required(),Select::make('category')->options(self::categories())->required(),Select::make('visibility')->options(['internal'=>'Internal','customer_visible'=>'Customer visible','worker_visible'=>'Worker visible'])->required(),Select::make('order_id')->relationship('order','order_number')->searchable(),Select::make('customer_id')->relationship('customer','email')->searchable(),Select::make('worker_profile_id')->relationship('workerProfile','display_name')->searchable(),Select::make('worker_document_id')->relationship('workerDocument','document_type')->searchable(),Select::make('assigned_to_id')->relationship('assignee','email')->searchable(),Textarea::make('summary')->columnSpanFull(),SpatieMediaLibraryFileUpload::make('attachments')->collection('support_ticket_attachments')->disk('local')->visibility('private')->multiple()->columnSpanFull()])]);}
 public static function infolist(Schema $s):Schema{return $s->components([View::make('filament.resources.support-tickets.view')->columnSpanFull()]);}
 public static function table(Table $t):Table{return $t->columns([TextColumn::make('ticket_number')->searchable(),TextColumn::make('status')->badge()->formatStateUsing(fn($s)=>str($s)->replace('_',' ')->title()),TextColumn::make('priority')->badge(),TextColumn::make('category')->formatStateUsing(fn($s)=>str($s)->replace('_',' ')->title()),TextColumn::make('subject')->limit(42),TextColumn::make('order.order_number'),TextColumn::make('assignee.name')->label('Assigned'),TextColumn::make('last_message_at')->since()->placeholder('No messages')])->filters([SelectFilter::make('status')->options(self::statuses()),SelectFilter::make('priority')->options(self::priorities()),SelectFilter::make('category')->options(self::categories()),Filter::make('assigned_to_me')->query(fn(Builder $q)=>$q->where('assigned_to_id',auth()->id())),Filter::make('unassigned')->query(fn(Builder $q)=>$q->whereNull('assigned_to_id')),Filter::make('urgent')->query(fn(Builder $q)=>$q->where('priority','urgent')),Filter::make('escalated')->query(fn(Builder $q)=>$q->where('status','escalated'))])->recordActions([ViewAction::make(),Action::make('note')->schema([Textarea::make('body')->required()])->action(fn(SupportTicket $r,array $data)=>app(SupportTicketService::class)->addMessage($r,['body'=>$data['body'],'message_type'=>'internal_note','visibility'=>'internal'],auth()->user())),Action::make('resolve')->schema([Textarea::make('note')->required()])->action(fn(SupportTicket $r,array $data)=>app(SupportTicketService::class)->resolveTicket($r,auth()->user(),$data['note'])),Action::make('assign_me')->action(fn(SupportTicket $r)=>app(SupportTicketService::class)->assignTicket($r,auth()->user(),auth()->user())),EditAction::make()]);}
 public static function getPages():array{return ['index'=>ListSupportTickets::route('/'),'create'=>CreateSupportTicket::route('/create'),'view'=>ViewSupportTicket::route('/{record}'),'edit'=>EditSupportTicket::route('/{record}/edit')];}
 public static function statuses():array{return array_combine($v=['open','pending_customer','pending_worker','pending_internal','escalated','resolved','closed'],array_map(fn($x)=>str($x)->replace('_',' ')->title()->toString(),$v));} public static function priorities():array{return array_combine($v=['low','normal','high','urgent'],array_map('ucfirst',$v));} public static function categories():array{return array_combine($v=['order_issue','delivery_issue','worker_issue','payment_issue','document_issue','customer_question','system_issue','other'],array_map(fn($x)=>str($x)->replace('_',' ')->title()->toString(),$v));}
}
