<?php
namespace App\Services\Workers; use App\Models\{User,WorkerAccountInvitation,WorkerApplication}; use Illuminate\Support\Facades\{DB,Hash}; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class WorkerAccountInvitationService {
 public function createInvitation(WorkerApplication $a,User $by):array{if($a->user_id)throw ValidationException::withMessages(['application'=>'Application already has a linked user.']);$raw=Str::random(64);$i=$a->invitations()->create(['invited_by_user_id'=>$by->id,'email'=>$a->email,'token_hash'=>hash('sha256',$raw),'status'=>'pending','expires_at'=>now()->addDays(7)]);app(WorkerOnboardingService::class)->recordApplicationEvent($a,'invitation.created',$a->status,$a->status,['invitation_id'=>$i->id],'Email delivery not connected; manual link required.');return ['invitation'=>$i,'token'=>$raw,'url'=>route('public.worker-invitations.show',['token'=>$raw])];}
 public function acceptInvitation(string $token,array $payload):User{$i=$this->resolve($token);return DB::transaction(function()use($i,$payload){if(User::where('email',$i->email)->exists())throw ValidationException::withMessages(['email'=>'A user account already exists for this email.']);$u=User::create(['name'=>$payload['name'],'email'=>$i->email,'password'=>Hash::make($payload['password'])]);$i->markAccepted($u);$this->linkExistingUser($i->application,$u,$u,'Invitation accepted.');app(WorkerOnboardingService::class)->recordApplicationEvent($i->application,'invitation.accepted',$i->application->status,$i->application->status,['invitation_id'=>$i->id]);return $u;});}
 public function linkExistingUser(WorkerApplication $a,User $u,User $actor,?string $note=null):void{if(strtolower($a->email)!==strtolower($u->email))throw ValidationException::withMessages(['user'=>'User email must match application email.']);$a->update(['user_id'=>$u->id]);app(WorkerOnboardingService::class)->recordApplicationEvent($a,'user.linked',$a->status,$a->status,['user_id'=>$u->id,'actor_id'=>$actor->id],$note);}
 public function cancelInvitation(WorkerAccountInvitation $i,User $actor,string $reason):void{if(trim($reason)==='')throw ValidationException::withMessages(['reason'=>'Cancellation reason is required.']);$i->markCancelled();app(WorkerOnboardingService::class)->recordApplicationEvent($i->application,'invitation.cancelled',$i->application->status,$i->application->status,['invitation_id'=>$i->id,'actor_id'=>$actor->id],$reason);}
 public function resolve(string $token):WorkerAccountInvitation{$i=WorkerAccountInvitation::with('application')->where('token_hash',hash('sha256',$token))->firstOrFail();if(!$i->isPending())throw ValidationException::withMessages(['invitation'=>$i->isExpired()?'Invitation expired.':'Invitation is not active.']);return $i;}
}
