<?php
namespace App\Services\Workers;
use App\Models\{User,WorkerApplication,WorkerApplicationEvent,WorkerProfile,WorkerStatusEvent};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
class WorkerOnboardingService {
 public function submitApplication(array $payload): WorkerApplication { return DB::transaction(function()use($payload){$payload['user_id']=User::where('email',$payload['email'])->value('id');$payload['status']='submitted';$payload['submitted_at']=now();$app=WorkerApplication::create($payload);$this->recordApplicationEvent($app,'application.submitted',null,'submitted');return $app;});}
 public function approve(WorkerApplication $app,User $reviewer,?string $note=null):WorkerProfile {if(!$app->user_id)throw ValidationException::withMessages(['application'=>'A matching existing user account is required before approval.']);return DB::transaction(function()use($app,$reviewer,$note){$caps=array_fill_keys(['can_deliver','can_move','can_handle_eco','can_do_handyman','can_tow','can_run_errands'],false);foreach($app->capabilities??[] as $c){$k=['delivery'=>'can_deliver','moving'=>'can_move','eco'=>'can_handle_eco','handyman'=>'can_do_handyman','towing'=>'can_tow','errands'=>'can_run_errands'][$c]??null;if($k)$caps[$k]=true;}$profile=WorkerProfile::updateOrCreate(['user_id'=>$app->user_id],array_merge($caps,['display_name'=>$app->name,'worker_type'=>$app->worker_type,'phone'=>$app->phone,'vehicle_type'=>$app->vehicle_type,'service_area'=>$app->desired_service_area,'status'=>'approved','approved_at'=>now(),'approved_by_user_id'=>$reviewer->id]));$from=$app->status;$app->update(['status'=>'approved','reviewed_at'=>now(),'reviewed_by_user_id'=>$reviewer->id,'decision_reason'=>$note]);$this->recordApplicationEvent($app,'application.approved',$from,'approved',[],$note);return $profile;});}
 public function reject(WorkerApplication $app,User $reviewer,string $reason):WorkerApplication {if(trim($reason)==='')throw ValidationException::withMessages(['reason'=>'Rejection reason is required.']);$from=$app->status;$app->update(['status'=>'rejected','reviewed_at'=>now(),'reviewed_by_user_id'=>$reviewer->id,'decision_reason'=>$reason]);$this->recordApplicationEvent($app,'application.rejected',$from,'rejected',[],$reason);return $app;}
 public function suspendProfile(WorkerProfile $profile,User $actor,string $reason):WorkerProfile {if(trim($reason)==='')throw ValidationException::withMessages(['reason'=>'Suspension reason is required.']);$from=$profile->status;$profile->update(['status'=>'suspended','rejection_reason'=>$reason]);$profile->availability?->update(['status'=>'offline']);WorkerStatusEvent::create(['user_id'=>$profile->user_id,'worker_profile_id'=>$profile->id,'actor_type'=>get_class($actor),'actor_id'=>$actor->id,'event_type'=>'worker.suspended','from_status'=>$from,'to_status'=>'suspended','note'=>$reason,'created_at'=>now()]);return $profile;}
 public function recordApplicationEvent(WorkerApplication $app,string $type,?string $from,?string $to,array $payload=[],?string $note=null):WorkerApplicationEvent{return $app->events()->create(['actor_type'=>auth()->check()?get_class(auth()->user()):null,'actor_id'=>auth()->id(),'event_type'=>$type,'from_status'=>$from,'to_status'=>$to,'payload'=>$payload?:null,'note'=>$note,'created_at'=>now()]);}
}
