<?php
namespace App\Services\Support;
use App\Models\{SupportMessage,SupportTicket,User};
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
class SupportTicketService {
 private const STATUSES=['open','pending_customer','pending_worker','pending_internal','escalated','resolved','closed'];
 private const PRIORITIES=['low','normal','high','urgent'];
 public function __construct(private SupportTicketNumberGenerator $numbers,private SupportNotificationService $notifications){}
 public function createTicket(array $data,User $actor):SupportTicket{$ticket=DB::transaction(function()use($data,$actor){$ticket=SupportTicket::create(['status'=>'open',...$data,'ticket_number'=>$this->numbers->generate(),'created_by_id'=>$actor->id]);$this->event($ticket,$actor,'created',null,$ticket->status,'Ticket created');return $ticket;});if($ticket->priority==='urgent')$this->notifications->urgentCreated($ticket);return $ticket;}
 public function addMessage(SupportTicket $ticket,array $data,User $actor):SupportMessage{$message=DB::transaction(function()use($ticket,$data,$actor){if(($data['message_type']??'internal_note')==='internal_note')$data['visibility']='internal';$message=$ticket->messages()->create([...$data,'author_id'=>$actor->id,'author_type'=>$data['author_type']??'support','is_system'=>false]);$ticket->update(['last_message_at'=>now()]);$this->event($ticket,$actor,'message_added',null,$message->message_type,'Message added',['message_id'=>$message->id,'visibility'=>$message->visibility]);return $message;});if($message->author_type==='customer')$this->notifications->customerReply($ticket);if($message->author_type==='worker')$this->notifications->workerReply($ticket);return $message;}
 public function assignTicket(SupportTicket $ticket,User $assignee,User $actor):SupportTicket{$ticket=DB::transaction(function()use($ticket,$assignee,$actor){$ticket->assignments()->where('status','active')->update(['status'=>'released','released_at'=>now(),'release_reason'=>'Reassigned']);$ticket->assignments()->create(['assigned_to_id'=>$assignee->id,'assigned_by_id'=>$actor->id,'status'=>'active','assigned_at'=>now()]);$from=$ticket->assigned_to_id;$ticket->update(['assigned_to_id'=>$assignee->id]);$this->event($ticket,$actor,'assigned',(string)$from,(string)$assignee->id,'Ticket assigned');return $ticket->refresh();});$this->notifications->assigned($ticket,$assignee);return $ticket;}
 public function changeStatus(SupportTicket $ticket,string $status,User $actor,?string $note=null):SupportTicket{if(!in_array($status,self::STATUSES,true))throw ValidationException::withMessages(['status'=>'Unsupported status.']);if(in_array($status,['escalated','resolved','closed'],true)&&blank($note))throw ValidationException::withMessages(['note'=>'A note is required for this status.']);$from=$ticket->status;$ticket->update(['status'=>$status,'closed_at'=>$status==='closed'?now():$ticket->closed_at]);$this->event($ticket,$actor,'status_changed',$from,$status,$note);return $ticket;}
 public function changePriority(SupportTicket $ticket,string $priority,User $actor,?string $note=null):SupportTicket{if(!in_array($priority,self::PRIORITIES,true))throw ValidationException::withMessages(['priority'=>'Unsupported priority.']);if($priority==='urgent'&&blank($note))throw ValidationException::withMessages(['note'=>'A note is required for urgent priority.']);$from=$ticket->priority;$ticket->update(['priority'=>$priority]);$this->event($ticket,$actor,'priority_changed',$from,$priority,$note);return $ticket;}
 public function resolveTicket(SupportTicket $ticket,User $actor,string $note):SupportTicket{if(blank($note))throw ValidationException::withMessages(['resolution_note'=>'Resolution note is required.']);$ticket->update(['status'=>'resolved','resolved_by_id'=>$actor->id,'resolved_at'=>now()]);$this->event($ticket,$actor,'resolved',null,'resolved',$note);$this->notifications->resolved($ticket);return $ticket;}
 public function reopenTicket(SupportTicket $ticket,User $actor,string $reason):SupportTicket{if(blank($reason))throw ValidationException::withMessages(['reason'=>'Reopen reason is required.']);$from=$ticket->status;$ticket->update(['status'=>'open','resolved_by_id'=>null,'resolved_at'=>null,'closed_at'=>null]);$this->event($ticket,$actor,'reopened',$from,'open',$reason);return $ticket;}
 public function attachFile(SupportTicket $ticket,string $path,User $actor):Media{return DB::transaction(function()use($ticket,$path,$actor){$media=$ticket->addMedia($path)->toMediaCollection('support_ticket_attachments','local');$this->event($ticket,$actor,'attachment_added',null,(string)$media->id,'Attachment added',['media_id'=>$media->id,'filename'=>$media->file_name]);activity()->performedOn($ticket)->causedBy($actor)->withProperties(['media_id'=>$media->id,'filename'=>$media->file_name])->log('support_ticket.attachment_added');return $media;});}
 private function event(SupportTicket $ticket,User $actor,string $type,?string $from,?string $to,?string $description=null,array $metadata=[]):void{$ticket->events()->create(['actor_id'=>$actor->id,'event_type'=>$type,'from_value'=>$from,'to_value'=>$to,'description'=>$description,'metadata'=>$metadata,'created_at'=>now()]);}
}
