<?php
namespace App\Filament\Pages;
use App\Models\{EvidenceRetentionJob,WorkerPayoutReviewEvidence};use App\Services\Security\{EvidenceRetentionJobService,FileScannerManager};use App\Settings\SecurityFileSettings;use Filament\Notifications\Notification;use Illuminate\Contracts\Support\Htmlable;
class SecurityFileScanner extends AdminOsModulePage {
 public string $scanner='disabled';public ?string $binaryPath=null,$retentionReason=null;public int $timeout=15;public bool $requireClean=true,$overrideEnabled=true,$retentionEnabled=false,$dryRunOnly=true;public ?int $retentionDays=365;
 protected static string|\BackedEnum|null $navigationIcon='heroicon-o-shield-check';protected static ?string $navigationLabel='Security File Scanner';protected static string|\UnitEnum|null $navigationGroup='System';protected static ?int $navigationSort=12;protected string $view='filament.pages.security-file-scanner';
 public function getModuleKey():string{return 'system';}public function getHeading():string|Htmlable{return '';}public static function canAccess():bool{return auth()->user()?->canAny(['admin.security.file_scanner.manage','admin.security.retention.view','admin.security.retention.approve'])??false;}
 public function mount():void{$s=app(SecurityFileSettings::class);$this->scanner=$s->security_file_scanner;$this->binaryPath=$s->clamav_binary_path;$this->timeout=$s->clamav_timeout_seconds;$this->requireClean=$s->evidence_download_requires_clean_scan;$this->overrideEnabled=$s->evidence_download_override_enabled;$this->retentionEnabled=$s->evidence_retention_enabled;$this->dryRunOnly=$s->evidence_retention_dry_run_only;$this->retentionDays=$s->evidence_retention_default_days;}
 public function saveSettings():void{$this->validate(['scanner'=>'required|in:disabled,clamav','binaryPath'=>'nullable|string|max:500','timeout'=>'required|integer|min:1|max:120','retentionDays'=>'nullable|integer|min:1|max:3650']);$s=app(SecurityFileSettings::class);$s->security_file_scanner=$this->scanner;$s->clamav_binary_path=$this->binaryPath;$s->clamav_timeout_seconds=$this->timeout;$s->evidence_download_requires_clean_scan=true;$s->evidence_download_override_enabled=$this->overrideEnabled;$s->evidence_retention_enabled=$this->retentionEnabled;$s->evidence_retention_dry_run_only=true;$s->evidence_retention_default_days=$this->retentionDays;$s->save();Notification::make()->title('Security settings saved. Physical deletion remains dry-run only.')->success()->send();}
 public function testScanner():void{$r=app(FileScannerManager::class)->getReadiness();Notification::make()->title($r['message'])->color($r['is_available']?'success':'danger')->send();}
 public function createDryRun():void{$j=app(EvidenceRetentionJobService::class)->createDryRun(auth()->user());Notification::make()->title("Retention dry run {$j->job_number}: {$j->candidate_count} candidate(s), no deletion.")->success()->send();}
 public function approveJob(int $id):void{$j=app(EvidenceRetentionJobService::class)->approveJob(EvidenceRetentionJob::findOrFail($id),auth()->user(),(string)$this->retentionReason);Notification::make()->title("{$j->job_number} approved. Execution remains separately gated.")->success()->send();$this->retentionReason=null;}
 public function executeJob(int $id):void{app(EvidenceRetentionJobService::class)->executeApprovedJob(EvidenceRetentionJob::findOrFail($id),auth()->user());}
 public function getViewData():array{return ['readiness'=>app(FileScannerManager::class)->getReadiness(),'counts'=>WorkerPayoutReviewEvidence::query()->selectRaw('scan_status, count(*) as total')->groupBy('scan_status')->pluck('total','scan_status'),'evidence'=>WorkerPayoutReviewEvidence::latest()->limit(20)->get(),'jobs'=>EvidenceRetentionJob::latest()->limit(10)->get(),'candidateCount'=>app(EvidenceRetentionJobService::class)->getCandidates()->count(),'securityUrl'=>route('filament.admin.pages.system-security')];}
}
