<?php
namespace App\Filament\Pages;
use App\Models\{EvidenceRetentionJobEvent,SecurityReviewerAccess,SecurityReviewerAccessEvent,WorkerPayoutReviewEvidence,WorkerPayoutReviewEvidenceEvent};use App\Services\Security\SecurityReviewerAccessService;use Filament\Notifications\Notification;use Illuminate\Contracts\Support\Htmlable;use Spatie\Permission\Models\Role;
class SecurityGovernance extends AdminOsModulePage {
 public ?string $reason=null;protected static string|\BackedEnum|null $navigationIcon='heroicon-o-key';protected static ?string $navigationLabel='Security Governance';protected static string|\UnitEnum|null $navigationGroup='System';protected static ?int $navigationSort=13;protected string $view='filament.pages.security-governance';
 public function getModuleKey():string{return 'system';}public function getHeading():string|Htmlable{return '';}public static function canAccess():bool{return auth()->user()?->hasAnyRole(['owner','admin','security_manager'])??false;}
 public function revoke(int $id):void{app(SecurityReviewerAccessService::class)->revokeAccess(SecurityReviewerAccess::findOrFail($id),auth()->user(),(string)$this->reason);$this->reason=null;Notification::make()->title('Reviewer access revoked; user account remains intact.')->success()->send();}
 public function suspend(int $id):void{app(SecurityReviewerAccessService::class)->suspendAccess(SecurityReviewerAccess::findOrFail($id),auth()->user(),(string)$this->reason);$this->reason=null;Notification::make()->title('Reviewer access suspended.')->success()->send();}
 public function getViewData():array{$summary=app(SecurityReviewerAccessService::class)->getSensitiveAccessSummary();$roles=Role::whereIn('name',['security_reviewer','compliance_reviewer','legal_reviewer','tax_reviewer','finance','owner','admin'])->with('permissions')->get();return compact('summary','roles')+['accesses'=>SecurityReviewerAccess::with('user.roles')->latest()->get(),'retentionEvents'=>EvidenceRetentionJobEvent::latest('created_at')->limit(20)->get(),'accessEvents'=>SecurityReviewerAccessEvent::latest('created_at')->limit(20)->get(),'overrideCount'=>WorkerPayoutReviewEvidenceEvent::where('event_type','download_override_used')->count(),'scanUnavailable'=>WorkerPayoutReviewEvidence::where('scan_status','scan_unavailable')->count()];}
}
