<?php
namespace App\Filament\Pages;
use App\Models\{EvidenceRetentionJobEvent,SecurityAccessReviewCycle,SecurityAuditExport,SecurityAuditExportRetentionJob,SecurityGovernanceNotification,SecurityIncident,SecurityReviewerAccess,SecurityReviewerAccessEvent,WorkerPayoutReviewEvidence,WorkerPayoutReviewEvidenceEvent};use App\Services\Security\{SecurityAccessReviewService,SecurityAuditExportService,SecurityGovernanceNotificationService,SecurityReviewerAccessService};use Filament\Notifications\Notification;use Illuminate\Contracts\Support\Htmlable;use Spatie\Permission\Models\Role;
class SecurityGovernance extends AdminOsModulePage {
 public ?string $reason=null;protected static string|\BackedEnum|null $navigationIcon='heroicon-o-key';protected static ?string $navigationLabel='Security Governance';protected static string|\UnitEnum|null $navigationGroup='System';protected static ?int $navigationSort=13;protected string $view='filament.pages.security-governance';
 public function getModuleKey():string{return 'system';}public function getHeading():string|Htmlable{return '';}public static function canAccess():bool{return auth()->user()?->hasAnyRole(['owner','admin','security_manager'])??false;}
 public function revoke(int $id):void{app(SecurityReviewerAccessService::class)->revokeAccess(SecurityReviewerAccess::findOrFail($id),auth()->user(),(string)$this->reason);$this->reason=null;Notification::make()->title('Reviewer access revoked; user account remains intact.')->success()->send();}
 public function suspend(int $id):void{app(SecurityReviewerAccessService::class)->suspendAccess(SecurityReviewerAccess::findOrFail($id),auth()->user(),(string)$this->reason);$this->reason=null;Notification::make()->title('Reviewer access suspended.')->success()->send();}
 public function createReviewCycle():void{$s=app(SecurityAccessReviewService::class);$c=$s->createCycle(auth()->user(),['notes'=>'Governance cockpit access review.']);$s->openCycle($c,auth()->user());$s->populateReviewerAccessItems($c,auth()->user());Notification::make()->title("Access review {$c->cycle_number} opened.")->success()->send();}
 public function escalateOverdue():void{$n=app(SecurityGovernanceNotificationService::class)->escalateOverdue(auth()->user());Notification::make()->title("{$n} overdue review escalation(s) recorded in-app.")->success()->send();}
 public function generateExport():void{$e=app(SecurityAuditExportService::class)->generateSecurityGovernanceExport(auth()->user());Notification::make()->title("Export {$e->export_number} generated with SHA-256.")->success()->send();}
 public function getViewData():array{$summary=app(SecurityReviewerAccessService::class)->getSensitiveAccessSummary();$review=app(SecurityAccessReviewService::class)->getAccessReviewReadiness();$notifications=app(SecurityGovernanceNotificationService::class)->getNotificationReadiness();$roles=Role::whereIn('name',['security_reviewer','compliance_reviewer','legal_reviewer','tax_reviewer','finance','owner','admin'])->with('permissions')->get();return compact('summary','review','notifications','roles')+['accesses'=>SecurityReviewerAccess::with('user.roles')->latest()->get(),'cycles'=>SecurityAccessReviewCycle::withCount('items')->latest()->limit(10)->get(),'governanceNotifications'=>SecurityGovernanceNotification::latest()->limit(20)->get(),'exports'=>SecurityAuditExport::latest()->limit(10)->get(),'exportRetentionJobs'=>SecurityAuditExportRetentionJob::latest()->limit(10)->get(),'incidents'=>SecurityIncident::latest()->limit(10)->get(),'retentionEvents'=>EvidenceRetentionJobEvent::latest('created_at')->limit(20)->get(),'accessEvents'=>SecurityReviewerAccessEvent::latest('created_at')->limit(20)->get(),'overrideCount'=>WorkerPayoutReviewEvidenceEvent::where('event_type','download_override_used')->count(),'scanUnavailable'=>WorkerPayoutReviewEvidence::where('scan_status','scan_unavailable')->count()];}
}
